// GERADO por .superpowers/sdd/2026-10-03-reforco-seguranca/mig/gerar-s3d.mjs (nunca editar à mão; rode o gerador de novo).
// Reforço de segurança S3d — md5 de ANTES|DEPOIS das funções redefinidas, textos novos (e neutros) e ACL exata das 19 tabelas,
// lidos da cópia 54422 (produção + S1 + S2; a S3a/S3b/S3c não tocam nada disto). Usado por seg-s3d-helpers.ts / seg-s3d.test.ts.
export const S3D_MD5: Record<string, { antes: string; depois: string }> = {
  "public.lancar_modelo(uuid,date,boolean)": { antes: "bc970584aef39ac8d5258b33c9cd7061", depois: "efe52aaad9a1e6055d758cf93e1950d5" },
  "public.conjunto_adicionar(uuid,uuid)": { antes: "2a50e68d81dc082db7f614a7a6a9b45d", depois: "6d64744f031fe3f1bb91b108dde59b92" },
  "public.conjunto_remover(uuid)": { antes: "cc26b50c101a0a20c2436d49356015dc", depois: "6cc0cb5557d7947228a54a1875ecbdda" },
  "public.salvar_grade_revenda(uuid,jsonb,integer)": { antes: "229622b44c073a14e1fa4e2eed21650f", depois: "c994305f2f9b4045a7631f4835f75602" },
  "public.salvar_produto_acabado(uuid,jsonb,jsonb)": { antes: "2fede16942ba6253ba6ad7bb65a38b18", depois: "b5c221a6ed46d43da732e411d523dd98" },
  "public.salvar_produto_acabado(uuid,jsonb,jsonb,integer)": { antes: "9a94559fb80bc83722c0a3bf889c4b1b", depois: "0c49981e9b459662cc2c6eda97de66d1" },
  "public.salvar_produto_importado(uuid,jsonb,jsonb,jsonb)": { antes: "c685d28c0d7b2dd74b0b4f3d5c4459e9", depois: "6fa4c5eeb72d6464d4b89a4027613c63" },
  "public.salvar_produto_importado(uuid,jsonb,jsonb,jsonb,integer)": { antes: "d64cbee1b0ad8722bdde2ff86d979f9e", depois: "22232a0b47eb0a23e3b464029fc84bbe" },
  "public.salvar_precos_fixo_produto_acabado(uuid,boolean,numeric,boolean,numeric)": { antes: "680d6d7fede3d2db47258396845f8fa7", depois: "815583deca5487c3c7b450d5e6db1bfc" },
  "public.salvar_precos_fixo_produto_importado(uuid,boolean,numeric,boolean,numeric)": { antes: "e5432858604e33a2dd785fc864ad89d5", depois: "a277b0dcc67cacf0658ba771cc8d87a7" },
  "public.salvar_markups_produto_acabado(uuid,numeric,numeric)": { antes: "acce9dfcf91dedac5c568ad8a2382885", depois: "1f266f1908cf4918b4a0a9d868565f92" },
  "public.criar_card_produto_acabado(uuid)": { antes: "0264cdac0549b0a6bfd7d5bf92e90f38", depois: "c6ef3b10eb543d5b3a78b5493ab44ab7" },
  "public.criar_cards_produto_acabado(uuid[])": { antes: "83fd36fafdd68dae108933257fd84b0c", depois: "26c9508a35f0a7f8df043c4104081db7" },
  "public.replicar_produtos_acabados(uuid,uuid,uuid[])": { antes: "d43b226864f0c5a12a345440910d0fdd", depois: "e7f84ef690b8df27df70259684d7866f" },
  "public.limpar_produto_acabado(uuid)": { antes: "964d18b0c9730ad21a5b6d9a9a03ee08", depois: "7317c0647ad53365216626974a01da52" },
  "public.excluir_produto_acabado(uuid)": { antes: "a791e603148b35732f212aa1ecc1b3d4", depois: "da21a97a40a1c275843b5ddb060ee9c5" },
  "public.aplicar_produto_ao_modelo(uuid)": { antes: "c6c9994f1a00edee787b4125fc2bb2ef", depois: "37767f8e85d765e77d65aef5502fec0f" },
  "public.criar_card_produto_importado(uuid)": { antes: "7546855157595eff70ac9f77790c994d", depois: "322e5ad33fe1ab7a5d6bbb9b81fee8a3" },
  "public.criar_cards_produto_importado(uuid[])": { antes: "105ccfe7874f39b4031e38db4706ad02", depois: "d63c1c9e0ec725ab722aaca02cbaba35" },
  "public.replicar_produtos_importados(uuid,uuid,uuid[])": { antes: "778443bdba406b32da722bc1ea8dca77", depois: "5a721131e7c2bcebd0fabcdc91d1a059" },
  "public.limpar_produto_importado(uuid)": { antes: "814f7c172ff20a59346c1a0a2097c158", depois: "9ae5447e55cbbc0125e5fa5d61bb4832" },
  "public.excluir_produto_importado(uuid)": { antes: "ecffacb8aac6179dfca1ad59b070e51e", depois: "850bb75f225e869006e874813edb61be" },
  "public.importar_modelo_linha(jsonb,jsonb)": { antes: "d115a79214c47214918dfa7136c22b72", depois: "db0c3dcbd90ded80d210b96747e01cb1" },
  "public.importar_produto_linha(jsonb,jsonb,text)": { antes: "fd00ccb80d28a79fed1f0b021e46e07f", depois: "ab10e6d4b3716634158e7b4d2983f438" },
  "public.integracao_salvar(jsonb,jsonb)": { antes: "18e1ecfc6d9856bad902e5c6bc9aaef3", depois: "0ffc0fa156efe213bf8fdcbb372dc52d" },
  "public.salvar_plan_tecido(uuid,jsonb,integer)": { antes: "50302aae4851bcd710ee7facec5ebc03", depois: "7b24a22b7a016ef433dfb9e1dc00c3d8" },
  "public._salvar_plan_tecido_core(uuid,jsonb,integer)": { antes: "81a3606444a2cf68ee376937009b9bad", depois: "9a5035ff6f73551f3b6b2c2890fc615a" },
  "public.plan_tecido_criar_cards(uuid,jsonb)": { antes: "88c22ce40dc15f88e08af185e23fbc08", depois: "2dfc1a5a28a15f3509b33e3576b6984f" },
  "public.plan_tecido_criar_card(uuid,jsonb)": { antes: "a2a4bb5de9793afb2711b50bef4970f7", depois: "425d69af538b519f91a19b1bc11d5175" },
  "public.plan_tecido_aplicar_ao_modelo(uuid,jsonb,boolean)": { antes: "25077223a646fdb8fd5db03ad65b0fc4", depois: "57583c7daf555eb7c177c1f20035b7cd" },
  "public.aplicar_plan_tecido_grade(uuid,jsonb)": { antes: "347219fb550ea1c342637ded5a80fa32", depois: "303be61997e21cbf640bf7fbc994f353" },
  "public.plan_tecido_fazer_pedido(uuid,jsonb,uuid[])": { antes: "48582c67c272cb30e4c6931f5f885e90", depois: "b5e982478d5dd1613581cf3af7f2fe7a" },
  "public.plan_tecido_desfazer_pedido(uuid)": { antes: "7df69a65ea9b64db4c8ca4c36c20e4ed", depois: "04dd8db196ebc5b336b839d244442556" },
  "public.plan_tecido_set_oc_aplicada(uuid,uuid[])": { antes: "71859c9c1004bf2ef43b1e610fed7bb9", depois: "5421535a8208d23621c896d4ec5eafbd" },
  "public.plan_tecido_set_paleta(uuid,jsonb)": { antes: "a26ae3008da0bf65acfd318f6cc3d2ae", depois: "bcaab2b542b798108ed0c0671eb23957" },
  "public.plan_tecido_set_pedido_fotos(uuid,text,text[])": { antes: "a15f8a31b4b36244d84e043931e1fdf2", depois: "65ec8a43da8c70b7fa5c3ddb75cb9742" },
  "public.plan_tecido_set_referencia(uuid,text[])": { antes: "307e56cdfb8945eb009d0834bd2f6843", depois: "8dc362667b1fb750fb56f12a51cd4732" },
  "public.plan_tecido_set_slot_oc(uuid,uuid,uuid[])": { antes: "0f7d3e3bec86a5dee9ddb77551e086cb", depois: "e192219b2dc68d736588031e83a5c015" },
  "public.replicar_cards_plan_tecido(uuid,uuid,uuid[],integer)": { antes: "a8172b9ffa18cb84e2db24beeb51eb41", depois: "6197f52f1ce32913c34bee4cfbb145b7" },
  "public.salvar_colecao_mix(uuid,uuid,text,text)": { antes: "b3c12a28bec8c7646f82c739c4b55055", depois: "9c1ded3dc7f51977020f72e7aabb026e" },
  "public.excluir_colecao_mix(uuid)": { antes: "d1131b0ddf792d87e92ea7db0ca89e2c", depois: "bded4fc594cd5a5dd026ed602ca95afc" },
};
/** Páginas do portão (OU) por RPC; [] = sem página nova (integracao_salvar, _salvar_plan_tecido_core = B3). */
export const S3D_PAGINAS: Record<string, string[]> = {
  "public.lancar_modelo(uuid,date,boolean)": ["criacao_planejamento","producao_lancamentos"],
  "public.conjunto_adicionar(uuid,uuid)": ["criacao_planejamento"],
  "public.conjunto_remover(uuid)": ["criacao_planejamento"],
  "public.salvar_grade_revenda(uuid,jsonb,integer)": ["criacao_planejamento","criacao_desenvolvimento"],
  "public.salvar_produto_acabado(uuid,jsonb,jsonb)": ["criacao_produto_acabado","criacao_planejamento"],
  "public.salvar_produto_acabado(uuid,jsonb,jsonb,integer)": ["criacao_produto_acabado","criacao_planejamento"],
  "public.salvar_produto_importado(uuid,jsonb,jsonb,jsonb)": ["criacao_produto_importado","criacao_planejamento"],
  "public.salvar_produto_importado(uuid,jsonb,jsonb,jsonb,integer)": ["criacao_produto_importado","criacao_planejamento"],
  "public.salvar_precos_fixo_produto_acabado(uuid,boolean,numeric,boolean,numeric)": ["criacao_produto_acabado","criacao_planejamento:preco_venda"],
  "public.salvar_precos_fixo_produto_importado(uuid,boolean,numeric,boolean,numeric)": ["criacao_produto_importado","criacao_planejamento:preco_venda"],
  "public.salvar_markups_produto_acabado(uuid,numeric,numeric)": ["criacao_produto_acabado","criacao_planejamento:preco_venda"],
  "public.criar_card_produto_acabado(uuid)": ["criacao_produto_acabado"],
  "public.criar_cards_produto_acabado(uuid[])": ["criacao_produto_acabado"],
  "public.replicar_produtos_acabados(uuid,uuid,uuid[])": ["criacao_produto_acabado"],
  "public.limpar_produto_acabado(uuid)": ["criacao_produto_acabado"],
  "public.excluir_produto_acabado(uuid)": ["criacao_produto_acabado"],
  "public.aplicar_produto_ao_modelo(uuid)": ["criacao_produto_acabado"],
  "public.criar_card_produto_importado(uuid)": ["criacao_produto_importado"],
  "public.criar_cards_produto_importado(uuid[])": ["criacao_produto_importado"],
  "public.replicar_produtos_importados(uuid,uuid,uuid[])": ["criacao_produto_importado"],
  "public.limpar_produto_importado(uuid)": ["criacao_produto_importado"],
  "public.excluir_produto_importado(uuid)": ["criacao_produto_importado"],
  "public.importar_modelo_linha(jsonb,jsonb)": ["importar"],
  "public.importar_produto_linha(jsonb,jsonb,text)": ["importar"],
  "public.integracao_salvar(jsonb,jsonb)": [],
  "public.salvar_plan_tecido(uuid,jsonb,integer)": ["criacao_plan_tecido"],
  "public._salvar_plan_tecido_core(uuid,jsonb,integer)": [],
  "public.plan_tecido_criar_cards(uuid,jsonb)": ["criacao_plan_tecido"],
  "public.plan_tecido_criar_card(uuid,jsonb)": ["criacao_plan_tecido"],
  "public.plan_tecido_aplicar_ao_modelo(uuid,jsonb,boolean)": ["criacao_plan_tecido"],
  "public.aplicar_plan_tecido_grade(uuid,jsonb)": ["criacao_plan_tecido"],
  "public.plan_tecido_fazer_pedido(uuid,jsonb,uuid[])": ["criacao_plan_tecido"],
  "public.plan_tecido_desfazer_pedido(uuid)": ["criacao_plan_tecido"],
  "public.plan_tecido_set_oc_aplicada(uuid,uuid[])": ["criacao_plan_tecido"],
  "public.plan_tecido_set_paleta(uuid,jsonb)": ["criacao_plan_tecido"],
  "public.plan_tecido_set_pedido_fotos(uuid,text,text[])": ["criacao_plan_tecido"],
  "public.plan_tecido_set_referencia(uuid,text[])": ["criacao_plan_tecido"],
  "public.plan_tecido_set_slot_oc(uuid,uuid,uuid[])": ["criacao_plan_tecido"],
  "public.replicar_cards_plan_tecido(uuid,uuid,uuid[],integer)": ["criacao_plan_tecido"],
  "public.salvar_colecao_mix(uuid,uuid,text,text)": ["criacao_plan_tecido","criacao_planejamento","criacao_produto_acabado","criacao_produto_importado"],
  "public.excluir_colecao_mix(uuid)": ["criacao_plan_tecido","criacao_planejamento","criacao_produto_acabado","criacao_produto_importado"],
};
export const S3D_GATILHOS: { tabela: string; fn: string; depois: string; neutra: string; tgtype: number; paginas: string[] }[] = [
  { tabela: "modelos", fn: "public.fn_seg_pagina_modelos()", depois: "f2e6579a764661ed6be0afe643050c6d", neutra: "382c59774ba779b27fcf2ebc6a0901be", tgtype: 31, paginas: ["criacao_planejamento","criacao_desenvolvimento","criacao_plan_tecido","criacao_produto_acabado","criacao_produto_importado"] },
  { tabela: "produtos_acabados", fn: "public.fn_seg_pagina_produtos_acabados()", depois: "d3faa369eeccc8759cb1ca1c195bde1c", neutra: "ab09f88a63e984fea51b9d6a5f3bccea", tgtype: 19, paginas: ["criacao_produto_acabado","criacao_planejamento"] },
  { tabela: "produtos_importados", fn: "public.fn_seg_pagina_produtos_importados()", depois: "854fefdd5519e875d5f2f6c947d086ae", neutra: "151187e6ad8c8c6ea168602b103185db", tgtype: 19, paginas: ["criacao_produto_importado","criacao_planejamento"] },
];
export const S3D_ACL: Record<string, { antes: [string, string | null]; depois: [string, string | null] }> = {
  modelos: { antes: ["{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", null], depois: ["{postgres=arwdDxtm/postgres,anon=rxtm/postgres,authenticated=arwdxtm/postgres,service_role=arwdDxtm/postgres}", null] },
  produtos_acabados: { antes: ["{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", null], depois: ["{postgres=arwdDxtm/postgres,anon=rxtm/postgres,authenticated=rxtm/postgres,service_role=arwdDxtm/postgres}", "modelo_id={authenticated=w/postgres} mix_id={authenticated=w/postgres}"] },
  produtos_importados: { antes: ["{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", null], depois: ["{postgres=arwdDxtm/postgres,anon=rxtm/postgres,authenticated=rxtm/postgres,service_role=arwdDxtm/postgres}", "modelo_id={authenticated=w/postgres} mix_id={authenticated=w/postgres}"] },
  produto_acabado_variantes: { antes: ["{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", null], depois: ["{postgres=arwdDxtm/postgres,anon=rxtm/postgres,authenticated=rxtm/postgres,service_role=arwdDxtm/postgres}", null] },
  produto_importado_variantes: { antes: ["{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", null], depois: ["{postgres=arwdDxtm/postgres,anon=rxtm/postgres,authenticated=rxtm/postgres,service_role=arwdDxtm/postgres}", null] },
  produto_importado_etapas: { antes: ["{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", null], depois: ["{postgres=arwdDxtm/postgres,anon=rxtm/postgres,authenticated=rxtm/postgres,service_role=arwdDxtm/postgres}", null] },
  plan_tecido: { antes: ["{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", null], depois: ["{postgres=arwdDxtm/postgres,anon=rxtm/postgres,authenticated=rxtm/postgres,service_role=arwdDxtm/postgres}", null] },
  plan_tecido_linhas: { antes: ["{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", null], depois: ["{postgres=arwdDxtm/postgres,anon=rxtm/postgres,authenticated=rxtm/postgres,service_role=arwdDxtm/postgres}", null] },
  plan_tecido_materiais: { antes: ["{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", null], depois: ["{postgres=arwdDxtm/postgres,anon=rxtm/postgres,authenticated=rxtm/postgres,service_role=arwdDxtm/postgres}", null] },
  plan_tecido_oc_aplicada: { antes: ["{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", null], depois: ["{postgres=arwdDxtm/postgres,anon=rxtm/postgres,authenticated=rxtm/postgres,service_role=arwdDxtm/postgres}", null] },
  plan_tecido_ocs: { antes: ["{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", null], depois: ["{postgres=arwdDxtm/postgres,anon=rxtm/postgres,authenticated=rxtm/postgres,service_role=arwdDxtm/postgres}", null] },
  plan_tecido_paleta: { antes: ["{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", null], depois: ["{postgres=arwdDxtm/postgres,anon=rxtm/postgres,authenticated=rxtm/postgres,service_role=arwdDxtm/postgres}", null] },
  plan_tecido_pedido_fotos: { antes: ["{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", null], depois: ["{postgres=arwdDxtm/postgres,anon=rxtm/postgres,authenticated=rxtm/postgres,service_role=arwdDxtm/postgres}", null] },
  plan_tecido_slot_oc: { antes: ["{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", null], depois: ["{postgres=arwdDxtm/postgres,anon=rxtm/postgres,authenticated=rxtm/postgres,service_role=arwdDxtm/postgres}", null] },
  plan_tecido_slots: { antes: ["{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", null], depois: ["{postgres=arwdDxtm/postgres,anon=rxtm/postgres,authenticated=rxtm/postgres,service_role=arwdDxtm/postgres}", null] },
  plan_tecido_snapshots: { antes: ["{postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres}", null], depois: ["{postgres=arwdDxtm/postgres,service_role=arwdDxtm/postgres,authenticated=r/postgres}", null] },
  plan_tecido_subcolecao_categorias: { antes: ["{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", null], depois: ["{postgres=arwdDxtm/postgres,anon=rxtm/postgres,authenticated=rxtm/postgres,service_role=arwdDxtm/postgres}", null] },
  plan_tecido_subcolecoes: { antes: ["{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", null], depois: ["{postgres=arwdDxtm/postgres,anon=rxtm/postgres,authenticated=rxtm/postgres,service_role=arwdDxtm/postgres}", null] },
  plan_tecido_variantes: { antes: ["{postgres=arwdDxtm/postgres,anon=arwdDxtm/postgres,authenticated=arwdDxtm/postgres,service_role=arwdDxtm/postgres}", null], depois: ["{postgres=arwdDxtm/postgres,anon=rxtm/postgres,authenticated=rxtm/postgres,service_role=arwdDxtm/postgres}", null] },
};
/** UPDATE por coluna do cliente (produtos: mix_id e modelo_id; modelos: a tabela inteira com o gatilho). */
export const S3D_COLUNAS_PRODUTO: string[] = ["mix_id","modelo_id"];
/** Só por RPC (o cliente só lê). plan_tecido_snapshots já era. */
export const S3D_SO_RPC: string[] = ["produto_acabado_variantes","produto_importado_variantes","produto_importado_etapas","plan_tecido","plan_tecido_linhas","plan_tecido_materiais","plan_tecido_oc_aplicada","plan_tecido_ocs","plan_tecido_paleta","plan_tecido_pedido_fotos","plan_tecido_slot_oc","plan_tecido_slots","plan_tecido_subcolecao_categorias","plan_tecido_subcolecoes","plan_tecido_variantes","plan_tecido_snapshots"];
/** As 13 do Plan. Tecido (o C2 da S4 deixa de ser preciso para escrita). */
export const S3D_PLAN_TECIDO: string[] = ["plan_tecido","plan_tecido_linhas","plan_tecido_materiais","plan_tecido_oc_aplicada","plan_tecido_ocs","plan_tecido_paleta","plan_tecido_pedido_fotos","plan_tecido_slot_oc","plan_tecido_slots","plan_tecido_snapshots","plan_tecido_subcolecao_categorias","plan_tecido_subcolecoes","plan_tecido_variantes"];
