/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProducaoRouteImport } from './routes/_authenticated/producao'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEntradaSaidaRouteImport } from './routes/_authenticated/entrada-saida'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCriacaoRouteImport } from './routes/_authenticated/criacao'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCadastroRouteImport } from './routes/_authenticated/cadastro'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedProducaoIndexRouteImport } from './routes/_authenticated/producao.index'
import { Route as AuthenticatedEntradaSaidaIndexRouteImport } from './routes/_authenticated/entrada-saida.index'
import { Route as AuthenticatedCriacaoIndexRouteImport } from './routes/_authenticated/criacao.index'
import { Route as AuthenticatedCadastroIndexRouteImport } from './routes/_authenticated/cadastro.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedProducaoTerceirizadosRouteImport } from './routes/_authenticated/producao.terceirizados'
import { Route as AuthenticatedProducaoOficinaRouteImport } from './routes/_authenticated/producao.oficina'
import { Route as AuthenticatedProducaoLancamentosRouteImport } from './routes/_authenticated/producao.lancamentos'
import { Route as AuthenticatedProducaoDirecionamentoRouteImport } from './routes/_authenticated/producao.direcionamento'
import { Route as AuthenticatedProducaoCqRouteImport } from './routes/_authenticated/producao.cq'
import { Route as AuthenticatedProducaoCadRouteImport } from './routes/_authenticated/producao.cad'
import { Route as AuthenticatedProducaoAcabamentoRouteImport } from './routes/_authenticated/producao.acabamento'
import { Route as AuthenticatedEntradaSaidaOcTecidoRouteImport } from './routes/_authenticated/entrada-saida.oc-tecido'
import { Route as AuthenticatedEntradaSaidaOcAviamentoRouteImport } from './routes/_authenticated/entrada-saida.oc-aviamento'
import { Route as AuthenticatedEntradaSaidaEstoqueRouteImport } from './routes/_authenticated/entrada-saida.estoque'
import { Route as AuthenticatedCriacaoPlanejamentoRouteImport } from './routes/_authenticated/criacao.planejamento'
import { Route as AuthenticatedCriacaoDesenvolvimentoRouteImport } from './routes/_authenticated/criacao.desenvolvimento'
import { Route as AuthenticatedCadastroTecidosRouteImport } from './routes/_authenticated/cadastro.tecidos'
import { Route as AuthenticatedCadastroServicoRouteImport } from './routes/_authenticated/cadastro.servico'
import { Route as AuthenticatedCadastroColaboradoresRouteImport } from './routes/_authenticated/cadastro.colaboradores'
import { Route as AuthenticatedCadastroAviamentosRouteImport } from './routes/_authenticated/cadastro.aviamentos'
import { Route as AuthenticatedCadastroAtributosRouteImport } from './routes/_authenticated/cadastro.atributos'
import { Route as AuthenticatedAdminUsuariosLojaRouteImport } from './routes/_authenticated/admin/usuarios-loja'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminLojasRouteImport } from './routes/_authenticated/admin/lojas'
import { Route as AuthenticatedAdminIdentidadeRouteImport } from './routes/_authenticated/admin/identidade'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as AuthenticatedProducaoTerceirizadosIndexRouteImport } from './routes/_authenticated/producao.terceirizados.index'
import { Route as AuthenticatedProducaoOficinaIndexRouteImport } from './routes/_authenticated/producao.oficina.index'
import { Route as AuthenticatedProducaoDirecionamentoIndexRouteImport } from './routes/_authenticated/producao.direcionamento.index'
import { Route as AuthenticatedProducaoCqIndexRouteImport } from './routes/_authenticated/producao.cq.index'
import { Route as AuthenticatedProducaoCadIndexRouteImport } from './routes/_authenticated/producao.cad.index'
import { Route as AuthenticatedProducaoAcabamentoIndexRouteImport } from './routes/_authenticated/producao.acabamento.index'
import { Route as AuthenticatedCadastroTecidosIndexRouteImport } from './routes/_authenticated/cadastro.tecidos.index'
import { Route as AuthenticatedProducaoTerceirizadosModeloIdRouteImport } from './routes/_authenticated/producao.terceirizados.$modeloId'
import { Route as AuthenticatedProducaoOficinaModeloIdRouteImport } from './routes/_authenticated/producao.oficina.$modeloId'
import { Route as AuthenticatedProducaoDirecionamentoModeloIdRouteImport } from './routes/_authenticated/producao.direcionamento.$modeloId'
import { Route as AuthenticatedProducaoCqModeloIdRouteImport } from './routes/_authenticated/producao.cq.$modeloId'
import { Route as AuthenticatedProducaoCadModeloIdRouteImport } from './routes/_authenticated/producao.cad.$modeloId'
import { Route as AuthenticatedProducaoAcabamentoModeloIdRouteImport } from './routes/_authenticated/producao.acabamento.$modeloId'
import { Route as AuthenticatedCadastroTecidosArtigoIdRouteImport } from './routes/_authenticated/cadastro.tecidos.$artigoId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProducaoRoute = AuthenticatedProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEntradaSaidaRoute =
  AuthenticatedEntradaSaidaRouteImport.update({
    id: '/entrada-saida',
    path: '/entrada-saida',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCriacaoRoute = AuthenticatedCriacaoRouteImport.update({
  id: '/criacao',
  path: '/criacao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastroRoute = AuthenticatedCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProducaoIndexRoute =
  AuthenticatedProducaoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProducaoRoute,
  } as any)
const AuthenticatedEntradaSaidaIndexRoute =
  AuthenticatedEntradaSaidaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEntradaSaidaRoute,
  } as any)
const AuthenticatedCriacaoIndexRoute =
  AuthenticatedCriacaoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCriacaoRoute,
  } as any)
const AuthenticatedCadastroIndexRoute =
  AuthenticatedCadastroIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCadastroRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedProducaoTerceirizadosRoute =
  AuthenticatedProducaoTerceirizadosRouteImport.update({
    id: '/terceirizados',
    path: '/terceirizados',
    getParentRoute: () => AuthenticatedProducaoRoute,
  } as any)
const AuthenticatedProducaoOficinaRoute =
  AuthenticatedProducaoOficinaRouteImport.update({
    id: '/oficina',
    path: '/oficina',
    getParentRoute: () => AuthenticatedProducaoRoute,
  } as any)
const AuthenticatedProducaoLancamentosRoute =
  AuthenticatedProducaoLancamentosRouteImport.update({
    id: '/lancamentos',
    path: '/lancamentos',
    getParentRoute: () => AuthenticatedProducaoRoute,
  } as any)
const AuthenticatedProducaoDirecionamentoRoute =
  AuthenticatedProducaoDirecionamentoRouteImport.update({
    id: '/direcionamento',
    path: '/direcionamento',
    getParentRoute: () => AuthenticatedProducaoRoute,
  } as any)
const AuthenticatedProducaoCqRoute = AuthenticatedProducaoCqRouteImport.update({
  id: '/cq',
  path: '/cq',
  getParentRoute: () => AuthenticatedProducaoRoute,
} as any)
const AuthenticatedProducaoCadRoute =
  AuthenticatedProducaoCadRouteImport.update({
    id: '/cad',
    path: '/cad',
    getParentRoute: () => AuthenticatedProducaoRoute,
  } as any)
const AuthenticatedProducaoAcabamentoRoute =
  AuthenticatedProducaoAcabamentoRouteImport.update({
    id: '/acabamento',
    path: '/acabamento',
    getParentRoute: () => AuthenticatedProducaoRoute,
  } as any)
const AuthenticatedEntradaSaidaOcTecidoRoute =
  AuthenticatedEntradaSaidaOcTecidoRouteImport.update({
    id: '/oc-tecido',
    path: '/oc-tecido',
    getParentRoute: () => AuthenticatedEntradaSaidaRoute,
  } as any)
const AuthenticatedEntradaSaidaOcAviamentoRoute =
  AuthenticatedEntradaSaidaOcAviamentoRouteImport.update({
    id: '/oc-aviamento',
    path: '/oc-aviamento',
    getParentRoute: () => AuthenticatedEntradaSaidaRoute,
  } as any)
const AuthenticatedEntradaSaidaEstoqueRoute =
  AuthenticatedEntradaSaidaEstoqueRouteImport.update({
    id: '/estoque',
    path: '/estoque',
    getParentRoute: () => AuthenticatedEntradaSaidaRoute,
  } as any)
const AuthenticatedCriacaoPlanejamentoRoute =
  AuthenticatedCriacaoPlanejamentoRouteImport.update({
    id: '/planejamento',
    path: '/planejamento',
    getParentRoute: () => AuthenticatedCriacaoRoute,
  } as any)
const AuthenticatedCriacaoDesenvolvimentoRoute =
  AuthenticatedCriacaoDesenvolvimentoRouteImport.update({
    id: '/desenvolvimento',
    path: '/desenvolvimento',
    getParentRoute: () => AuthenticatedCriacaoRoute,
  } as any)
const AuthenticatedCadastroTecidosRoute =
  AuthenticatedCadastroTecidosRouteImport.update({
    id: '/tecidos',
    path: '/tecidos',
    getParentRoute: () => AuthenticatedCadastroRoute,
  } as any)
const AuthenticatedCadastroServicoRoute =
  AuthenticatedCadastroServicoRouteImport.update({
    id: '/servico',
    path: '/servico',
    getParentRoute: () => AuthenticatedCadastroRoute,
  } as any)
const AuthenticatedCadastroColaboradoresRoute =
  AuthenticatedCadastroColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedCadastroRoute,
  } as any)
const AuthenticatedCadastroAviamentosRoute =
  AuthenticatedCadastroAviamentosRouteImport.update({
    id: '/aviamentos',
    path: '/aviamentos',
    getParentRoute: () => AuthenticatedCadastroRoute,
  } as any)
const AuthenticatedCadastroAtributosRoute =
  AuthenticatedCadastroAtributosRouteImport.update({
    id: '/atributos',
    path: '/atributos',
    getParentRoute: () => AuthenticatedCadastroRoute,
  } as any)
const AuthenticatedAdminUsuariosLojaRoute =
  AuthenticatedAdminUsuariosLojaRouteImport.update({
    id: '/usuarios-loja',
    path: '/usuarios-loja',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLojasRoute = AuthenticatedAdminLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminIdentidadeRoute =
  AuthenticatedAdminIdentidadeRouteImport.update({
    id: '/identidade',
    path: '/identidade',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedProducaoTerceirizadosIndexRoute =
  AuthenticatedProducaoTerceirizadosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProducaoTerceirizadosRoute,
  } as any)
const AuthenticatedProducaoOficinaIndexRoute =
  AuthenticatedProducaoOficinaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProducaoOficinaRoute,
  } as any)
const AuthenticatedProducaoDirecionamentoIndexRoute =
  AuthenticatedProducaoDirecionamentoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProducaoDirecionamentoRoute,
  } as any)
const AuthenticatedProducaoCqIndexRoute =
  AuthenticatedProducaoCqIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProducaoCqRoute,
  } as any)
const AuthenticatedProducaoCadIndexRoute =
  AuthenticatedProducaoCadIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProducaoCadRoute,
  } as any)
const AuthenticatedProducaoAcabamentoIndexRoute =
  AuthenticatedProducaoAcabamentoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProducaoAcabamentoRoute,
  } as any)
const AuthenticatedCadastroTecidosIndexRoute =
  AuthenticatedCadastroTecidosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCadastroTecidosRoute,
  } as any)
const AuthenticatedProducaoTerceirizadosModeloIdRoute =
  AuthenticatedProducaoTerceirizadosModeloIdRouteImport.update({
    id: '/$modeloId',
    path: '/$modeloId',
    getParentRoute: () => AuthenticatedProducaoTerceirizadosRoute,
  } as any)
const AuthenticatedProducaoOficinaModeloIdRoute =
  AuthenticatedProducaoOficinaModeloIdRouteImport.update({
    id: '/$modeloId',
    path: '/$modeloId',
    getParentRoute: () => AuthenticatedProducaoOficinaRoute,
  } as any)
const AuthenticatedProducaoDirecionamentoModeloIdRoute =
  AuthenticatedProducaoDirecionamentoModeloIdRouteImport.update({
    id: '/$modeloId',
    path: '/$modeloId',
    getParentRoute: () => AuthenticatedProducaoDirecionamentoRoute,
  } as any)
const AuthenticatedProducaoCqModeloIdRoute =
  AuthenticatedProducaoCqModeloIdRouteImport.update({
    id: '/$modeloId',
    path: '/$modeloId',
    getParentRoute: () => AuthenticatedProducaoCqRoute,
  } as any)
const AuthenticatedProducaoCadModeloIdRoute =
  AuthenticatedProducaoCadModeloIdRouteImport.update({
    id: '/$modeloId',
    path: '/$modeloId',
    getParentRoute: () => AuthenticatedProducaoCadRoute,
  } as any)
const AuthenticatedProducaoAcabamentoModeloIdRoute =
  AuthenticatedProducaoAcabamentoModeloIdRouteImport.update({
    id: '/$modeloId',
    path: '/$modeloId',
    getParentRoute: () => AuthenticatedProducaoAcabamentoRoute,
  } as any)
const AuthenticatedCadastroTecidosArtigoIdRoute =
  AuthenticatedCadastroTecidosArtigoIdRouteImport.update({
    id: '/$artigoId',
    path: '/$artigoId',
    getParentRoute: () => AuthenticatedCadastroTecidosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/cadastro': typeof AuthenticatedCadastroRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/criacao': typeof AuthenticatedCriacaoRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entrada-saida': typeof AuthenticatedEntradaSaidaRouteWithChildren
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/producao': typeof AuthenticatedProducaoRouteWithChildren
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/identidade': typeof AuthenticatedAdminIdentidadeRoute
  '/admin/lojas': typeof AuthenticatedAdminLojasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/usuarios-loja': typeof AuthenticatedAdminUsuariosLojaRoute
  '/cadastro/atributos': typeof AuthenticatedCadastroAtributosRoute
  '/cadastro/aviamentos': typeof AuthenticatedCadastroAviamentosRoute
  '/cadastro/colaboradores': typeof AuthenticatedCadastroColaboradoresRoute
  '/cadastro/servico': typeof AuthenticatedCadastroServicoRoute
  '/cadastro/tecidos': typeof AuthenticatedCadastroTecidosRouteWithChildren
  '/criacao/desenvolvimento': typeof AuthenticatedCriacaoDesenvolvimentoRoute
  '/criacao/planejamento': typeof AuthenticatedCriacaoPlanejamentoRoute
  '/entrada-saida/estoque': typeof AuthenticatedEntradaSaidaEstoqueRoute
  '/entrada-saida/oc-aviamento': typeof AuthenticatedEntradaSaidaOcAviamentoRoute
  '/entrada-saida/oc-tecido': typeof AuthenticatedEntradaSaidaOcTecidoRoute
  '/producao/acabamento': typeof AuthenticatedProducaoAcabamentoRouteWithChildren
  '/producao/cad': typeof AuthenticatedProducaoCadRouteWithChildren
  '/producao/cq': typeof AuthenticatedProducaoCqRouteWithChildren
  '/producao/direcionamento': typeof AuthenticatedProducaoDirecionamentoRouteWithChildren
  '/producao/lancamentos': typeof AuthenticatedProducaoLancamentosRoute
  '/producao/oficina': typeof AuthenticatedProducaoOficinaRouteWithChildren
  '/producao/terceirizados': typeof AuthenticatedProducaoTerceirizadosRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/cadastro/': typeof AuthenticatedCadastroIndexRoute
  '/criacao/': typeof AuthenticatedCriacaoIndexRoute
  '/entrada-saida/': typeof AuthenticatedEntradaSaidaIndexRoute
  '/producao/': typeof AuthenticatedProducaoIndexRoute
  '/cadastro/tecidos/$artigoId': typeof AuthenticatedCadastroTecidosArtigoIdRoute
  '/producao/acabamento/$modeloId': typeof AuthenticatedProducaoAcabamentoModeloIdRoute
  '/producao/cad/$modeloId': typeof AuthenticatedProducaoCadModeloIdRoute
  '/producao/cq/$modeloId': typeof AuthenticatedProducaoCqModeloIdRoute
  '/producao/direcionamento/$modeloId': typeof AuthenticatedProducaoDirecionamentoModeloIdRoute
  '/producao/oficina/$modeloId': typeof AuthenticatedProducaoOficinaModeloIdRoute
  '/producao/terceirizados/$modeloId': typeof AuthenticatedProducaoTerceirizadosModeloIdRoute
  '/cadastro/tecidos/': typeof AuthenticatedCadastroTecidosIndexRoute
  '/producao/acabamento/': typeof AuthenticatedProducaoAcabamentoIndexRoute
  '/producao/cad/': typeof AuthenticatedProducaoCadIndexRoute
  '/producao/cq/': typeof AuthenticatedProducaoCqIndexRoute
  '/producao/direcionamento/': typeof AuthenticatedProducaoDirecionamentoIndexRoute
  '/producao/oficina/': typeof AuthenticatedProducaoOficinaIndexRoute
  '/producao/terceirizados/': typeof AuthenticatedProducaoTerceirizadosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/identidade': typeof AuthenticatedAdminIdentidadeRoute
  '/admin/lojas': typeof AuthenticatedAdminLojasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/usuarios-loja': typeof AuthenticatedAdminUsuariosLojaRoute
  '/cadastro/atributos': typeof AuthenticatedCadastroAtributosRoute
  '/cadastro/aviamentos': typeof AuthenticatedCadastroAviamentosRoute
  '/cadastro/colaboradores': typeof AuthenticatedCadastroColaboradoresRoute
  '/cadastro/servico': typeof AuthenticatedCadastroServicoRoute
  '/criacao/desenvolvimento': typeof AuthenticatedCriacaoDesenvolvimentoRoute
  '/criacao/planejamento': typeof AuthenticatedCriacaoPlanejamentoRoute
  '/entrada-saida/estoque': typeof AuthenticatedEntradaSaidaEstoqueRoute
  '/entrada-saida/oc-aviamento': typeof AuthenticatedEntradaSaidaOcAviamentoRoute
  '/entrada-saida/oc-tecido': typeof AuthenticatedEntradaSaidaOcTecidoRoute
  '/producao/lancamentos': typeof AuthenticatedProducaoLancamentosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/cadastro': typeof AuthenticatedCadastroIndexRoute
  '/criacao': typeof AuthenticatedCriacaoIndexRoute
  '/entrada-saida': typeof AuthenticatedEntradaSaidaIndexRoute
  '/producao': typeof AuthenticatedProducaoIndexRoute
  '/cadastro/tecidos/$artigoId': typeof AuthenticatedCadastroTecidosArtigoIdRoute
  '/producao/acabamento/$modeloId': typeof AuthenticatedProducaoAcabamentoModeloIdRoute
  '/producao/cad/$modeloId': typeof AuthenticatedProducaoCadModeloIdRoute
  '/producao/cq/$modeloId': typeof AuthenticatedProducaoCqModeloIdRoute
  '/producao/direcionamento/$modeloId': typeof AuthenticatedProducaoDirecionamentoModeloIdRoute
  '/producao/oficina/$modeloId': typeof AuthenticatedProducaoOficinaModeloIdRoute
  '/producao/terceirizados/$modeloId': typeof AuthenticatedProducaoTerceirizadosModeloIdRoute
  '/cadastro/tecidos': typeof AuthenticatedCadastroTecidosIndexRoute
  '/producao/acabamento': typeof AuthenticatedProducaoAcabamentoIndexRoute
  '/producao/cad': typeof AuthenticatedProducaoCadIndexRoute
  '/producao/cq': typeof AuthenticatedProducaoCqIndexRoute
  '/producao/direcionamento': typeof AuthenticatedProducaoDirecionamentoIndexRoute
  '/producao/oficina': typeof AuthenticatedProducaoOficinaIndexRoute
  '/producao/terceirizados': typeof AuthenticatedProducaoTerceirizadosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/cadastro': typeof AuthenticatedCadastroRouteWithChildren
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/criacao': typeof AuthenticatedCriacaoRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/entrada-saida': typeof AuthenticatedEntradaSaidaRouteWithChildren
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/producao': typeof AuthenticatedProducaoRouteWithChildren
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/identidade': typeof AuthenticatedAdminIdentidadeRoute
  '/_authenticated/admin/lojas': typeof AuthenticatedAdminLojasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/usuarios-loja': typeof AuthenticatedAdminUsuariosLojaRoute
  '/_authenticated/cadastro/atributos': typeof AuthenticatedCadastroAtributosRoute
  '/_authenticated/cadastro/aviamentos': typeof AuthenticatedCadastroAviamentosRoute
  '/_authenticated/cadastro/colaboradores': typeof AuthenticatedCadastroColaboradoresRoute
  '/_authenticated/cadastro/servico': typeof AuthenticatedCadastroServicoRoute
  '/_authenticated/cadastro/tecidos': typeof AuthenticatedCadastroTecidosRouteWithChildren
  '/_authenticated/criacao/desenvolvimento': typeof AuthenticatedCriacaoDesenvolvimentoRoute
  '/_authenticated/criacao/planejamento': typeof AuthenticatedCriacaoPlanejamentoRoute
  '/_authenticated/entrada-saida/estoque': typeof AuthenticatedEntradaSaidaEstoqueRoute
  '/_authenticated/entrada-saida/oc-aviamento': typeof AuthenticatedEntradaSaidaOcAviamentoRoute
  '/_authenticated/entrada-saida/oc-tecido': typeof AuthenticatedEntradaSaidaOcTecidoRoute
  '/_authenticated/producao/acabamento': typeof AuthenticatedProducaoAcabamentoRouteWithChildren
  '/_authenticated/producao/cad': typeof AuthenticatedProducaoCadRouteWithChildren
  '/_authenticated/producao/cq': typeof AuthenticatedProducaoCqRouteWithChildren
  '/_authenticated/producao/direcionamento': typeof AuthenticatedProducaoDirecionamentoRouteWithChildren
  '/_authenticated/producao/lancamentos': typeof AuthenticatedProducaoLancamentosRoute
  '/_authenticated/producao/oficina': typeof AuthenticatedProducaoOficinaRouteWithChildren
  '/_authenticated/producao/terceirizados': typeof AuthenticatedProducaoTerceirizadosRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/cadastro/': typeof AuthenticatedCadastroIndexRoute
  '/_authenticated/criacao/': typeof AuthenticatedCriacaoIndexRoute
  '/_authenticated/entrada-saida/': typeof AuthenticatedEntradaSaidaIndexRoute
  '/_authenticated/producao/': typeof AuthenticatedProducaoIndexRoute
  '/_authenticated/cadastro/tecidos/$artigoId': typeof AuthenticatedCadastroTecidosArtigoIdRoute
  '/_authenticated/producao/acabamento/$modeloId': typeof AuthenticatedProducaoAcabamentoModeloIdRoute
  '/_authenticated/producao/cad/$modeloId': typeof AuthenticatedProducaoCadModeloIdRoute
  '/_authenticated/producao/cq/$modeloId': typeof AuthenticatedProducaoCqModeloIdRoute
  '/_authenticated/producao/direcionamento/$modeloId': typeof AuthenticatedProducaoDirecionamentoModeloIdRoute
  '/_authenticated/producao/oficina/$modeloId': typeof AuthenticatedProducaoOficinaModeloIdRoute
  '/_authenticated/producao/terceirizados/$modeloId': typeof AuthenticatedProducaoTerceirizadosModeloIdRoute
  '/_authenticated/cadastro/tecidos/': typeof AuthenticatedCadastroTecidosIndexRoute
  '/_authenticated/producao/acabamento/': typeof AuthenticatedProducaoAcabamentoIndexRoute
  '/_authenticated/producao/cad/': typeof AuthenticatedProducaoCadIndexRoute
  '/_authenticated/producao/cq/': typeof AuthenticatedProducaoCqIndexRoute
  '/_authenticated/producao/direcionamento/': typeof AuthenticatedProducaoDirecionamentoIndexRoute
  '/_authenticated/producao/oficina/': typeof AuthenticatedProducaoOficinaIndexRoute
  '/_authenticated/producao/terceirizados/': typeof AuthenticatedProducaoTerceirizadosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/cadastro'
    | '/configuracoes'
    | '/criacao'
    | '/dashboard'
    | '/entrada-saida'
    | '/financeiro'
    | '/producao'
    | '/admin/configuracoes'
    | '/admin/identidade'
    | '/admin/lojas'
    | '/admin/usuarios'
    | '/admin/usuarios-loja'
    | '/cadastro/atributos'
    | '/cadastro/aviamentos'
    | '/cadastro/colaboradores'
    | '/cadastro/servico'
    | '/cadastro/tecidos'
    | '/criacao/desenvolvimento'
    | '/criacao/planejamento'
    | '/entrada-saida/estoque'
    | '/entrada-saida/oc-aviamento'
    | '/entrada-saida/oc-tecido'
    | '/producao/acabamento'
    | '/producao/cad'
    | '/producao/cq'
    | '/producao/direcionamento'
    | '/producao/lancamentos'
    | '/producao/oficina'
    | '/producao/terceirizados'
    | '/admin/'
    | '/cadastro/'
    | '/criacao/'
    | '/entrada-saida/'
    | '/producao/'
    | '/cadastro/tecidos/$artigoId'
    | '/producao/acabamento/$modeloId'
    | '/producao/cad/$modeloId'
    | '/producao/cq/$modeloId'
    | '/producao/direcionamento/$modeloId'
    | '/producao/oficina/$modeloId'
    | '/producao/terceirizados/$modeloId'
    | '/cadastro/tecidos/'
    | '/producao/acabamento/'
    | '/producao/cad/'
    | '/producao/cq/'
    | '/producao/direcionamento/'
    | '/producao/oficina/'
    | '/producao/terceirizados/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/admin/configuracoes'
    | '/admin/identidade'
    | '/admin/lojas'
    | '/admin/usuarios'
    | '/admin/usuarios-loja'
    | '/cadastro/atributos'
    | '/cadastro/aviamentos'
    | '/cadastro/colaboradores'
    | '/cadastro/servico'
    | '/criacao/desenvolvimento'
    | '/criacao/planejamento'
    | '/entrada-saida/estoque'
    | '/entrada-saida/oc-aviamento'
    | '/entrada-saida/oc-tecido'
    | '/producao/lancamentos'
    | '/admin'
    | '/cadastro'
    | '/criacao'
    | '/entrada-saida'
    | '/producao'
    | '/cadastro/tecidos/$artigoId'
    | '/producao/acabamento/$modeloId'
    | '/producao/cad/$modeloId'
    | '/producao/cq/$modeloId'
    | '/producao/direcionamento/$modeloId'
    | '/producao/oficina/$modeloId'
    | '/producao/terceirizados/$modeloId'
    | '/cadastro/tecidos'
    | '/producao/acabamento'
    | '/producao/cad'
    | '/producao/cq'
    | '/producao/direcionamento'
    | '/producao/oficina'
    | '/producao/terceirizados'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/cadastro'
    | '/_authenticated/configuracoes'
    | '/_authenticated/criacao'
    | '/_authenticated/dashboard'
    | '/_authenticated/entrada-saida'
    | '/_authenticated/financeiro'
    | '/_authenticated/producao'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/identidade'
    | '/_authenticated/admin/lojas'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/usuarios-loja'
    | '/_authenticated/cadastro/atributos'
    | '/_authenticated/cadastro/aviamentos'
    | '/_authenticated/cadastro/colaboradores'
    | '/_authenticated/cadastro/servico'
    | '/_authenticated/cadastro/tecidos'
    | '/_authenticated/criacao/desenvolvimento'
    | '/_authenticated/criacao/planejamento'
    | '/_authenticated/entrada-saida/estoque'
    | '/_authenticated/entrada-saida/oc-aviamento'
    | '/_authenticated/entrada-saida/oc-tecido'
    | '/_authenticated/producao/acabamento'
    | '/_authenticated/producao/cad'
    | '/_authenticated/producao/cq'
    | '/_authenticated/producao/direcionamento'
    | '/_authenticated/producao/lancamentos'
    | '/_authenticated/producao/oficina'
    | '/_authenticated/producao/terceirizados'
    | '/_authenticated/admin/'
    | '/_authenticated/cadastro/'
    | '/_authenticated/criacao/'
    | '/_authenticated/entrada-saida/'
    | '/_authenticated/producao/'
    | '/_authenticated/cadastro/tecidos/$artigoId'
    | '/_authenticated/producao/acabamento/$modeloId'
    | '/_authenticated/producao/cad/$modeloId'
    | '/_authenticated/producao/cq/$modeloId'
    | '/_authenticated/producao/direcionamento/$modeloId'
    | '/_authenticated/producao/oficina/$modeloId'
    | '/_authenticated/producao/terceirizados/$modeloId'
    | '/_authenticated/cadastro/tecidos/'
    | '/_authenticated/producao/acabamento/'
    | '/_authenticated/producao/cad/'
    | '/_authenticated/producao/cq/'
    | '/_authenticated/producao/direcionamento/'
    | '/_authenticated/producao/oficina/'
    | '/_authenticated/producao/terceirizados/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/producao': {
      id: '/_authenticated/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AuthenticatedProducaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entrada-saida': {
      id: '/_authenticated/entrada-saida'
      path: '/entrada-saida'
      fullPath: '/entrada-saida'
      preLoaderRoute: typeof AuthenticatedEntradaSaidaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/criacao': {
      id: '/_authenticated/criacao'
      path: '/criacao'
      fullPath: '/criacao'
      preLoaderRoute: typeof AuthenticatedCriacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro': {
      id: '/_authenticated/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof AuthenticatedCadastroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/producao/': {
      id: '/_authenticated/producao/'
      path: '/'
      fullPath: '/producao/'
      preLoaderRoute: typeof AuthenticatedProducaoIndexRouteImport
      parentRoute: typeof AuthenticatedProducaoRoute
    }
    '/_authenticated/entrada-saida/': {
      id: '/_authenticated/entrada-saida/'
      path: '/'
      fullPath: '/entrada-saida/'
      preLoaderRoute: typeof AuthenticatedEntradaSaidaIndexRouteImport
      parentRoute: typeof AuthenticatedEntradaSaidaRoute
    }
    '/_authenticated/criacao/': {
      id: '/_authenticated/criacao/'
      path: '/'
      fullPath: '/criacao/'
      preLoaderRoute: typeof AuthenticatedCriacaoIndexRouteImport
      parentRoute: typeof AuthenticatedCriacaoRoute
    }
    '/_authenticated/cadastro/': {
      id: '/_authenticated/cadastro/'
      path: '/'
      fullPath: '/cadastro/'
      preLoaderRoute: typeof AuthenticatedCadastroIndexRouteImport
      parentRoute: typeof AuthenticatedCadastroRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/producao/terceirizados': {
      id: '/_authenticated/producao/terceirizados'
      path: '/terceirizados'
      fullPath: '/producao/terceirizados'
      preLoaderRoute: typeof AuthenticatedProducaoTerceirizadosRouteImport
      parentRoute: typeof AuthenticatedProducaoRoute
    }
    '/_authenticated/producao/oficina': {
      id: '/_authenticated/producao/oficina'
      path: '/oficina'
      fullPath: '/producao/oficina'
      preLoaderRoute: typeof AuthenticatedProducaoOficinaRouteImport
      parentRoute: typeof AuthenticatedProducaoRoute
    }
    '/_authenticated/producao/lancamentos': {
      id: '/_authenticated/producao/lancamentos'
      path: '/lancamentos'
      fullPath: '/producao/lancamentos'
      preLoaderRoute: typeof AuthenticatedProducaoLancamentosRouteImport
      parentRoute: typeof AuthenticatedProducaoRoute
    }
    '/_authenticated/producao/direcionamento': {
      id: '/_authenticated/producao/direcionamento'
      path: '/direcionamento'
      fullPath: '/producao/direcionamento'
      preLoaderRoute: typeof AuthenticatedProducaoDirecionamentoRouteImport
      parentRoute: typeof AuthenticatedProducaoRoute
    }
    '/_authenticated/producao/cq': {
      id: '/_authenticated/producao/cq'
      path: '/cq'
      fullPath: '/producao/cq'
      preLoaderRoute: typeof AuthenticatedProducaoCqRouteImport
      parentRoute: typeof AuthenticatedProducaoRoute
    }
    '/_authenticated/producao/cad': {
      id: '/_authenticated/producao/cad'
      path: '/cad'
      fullPath: '/producao/cad'
      preLoaderRoute: typeof AuthenticatedProducaoCadRouteImport
      parentRoute: typeof AuthenticatedProducaoRoute
    }
    '/_authenticated/producao/acabamento': {
      id: '/_authenticated/producao/acabamento'
      path: '/acabamento'
      fullPath: '/producao/acabamento'
      preLoaderRoute: typeof AuthenticatedProducaoAcabamentoRouteImport
      parentRoute: typeof AuthenticatedProducaoRoute
    }
    '/_authenticated/entrada-saida/oc-tecido': {
      id: '/_authenticated/entrada-saida/oc-tecido'
      path: '/oc-tecido'
      fullPath: '/entrada-saida/oc-tecido'
      preLoaderRoute: typeof AuthenticatedEntradaSaidaOcTecidoRouteImport
      parentRoute: typeof AuthenticatedEntradaSaidaRoute
    }
    '/_authenticated/entrada-saida/oc-aviamento': {
      id: '/_authenticated/entrada-saida/oc-aviamento'
      path: '/oc-aviamento'
      fullPath: '/entrada-saida/oc-aviamento'
      preLoaderRoute: typeof AuthenticatedEntradaSaidaOcAviamentoRouteImport
      parentRoute: typeof AuthenticatedEntradaSaidaRoute
    }
    '/_authenticated/entrada-saida/estoque': {
      id: '/_authenticated/entrada-saida/estoque'
      path: '/estoque'
      fullPath: '/entrada-saida/estoque'
      preLoaderRoute: typeof AuthenticatedEntradaSaidaEstoqueRouteImport
      parentRoute: typeof AuthenticatedEntradaSaidaRoute
    }
    '/_authenticated/criacao/planejamento': {
      id: '/_authenticated/criacao/planejamento'
      path: '/planejamento'
      fullPath: '/criacao/planejamento'
      preLoaderRoute: typeof AuthenticatedCriacaoPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedCriacaoRoute
    }
    '/_authenticated/criacao/desenvolvimento': {
      id: '/_authenticated/criacao/desenvolvimento'
      path: '/desenvolvimento'
      fullPath: '/criacao/desenvolvimento'
      preLoaderRoute: typeof AuthenticatedCriacaoDesenvolvimentoRouteImport
      parentRoute: typeof AuthenticatedCriacaoRoute
    }
    '/_authenticated/cadastro/tecidos': {
      id: '/_authenticated/cadastro/tecidos'
      path: '/tecidos'
      fullPath: '/cadastro/tecidos'
      preLoaderRoute: typeof AuthenticatedCadastroTecidosRouteImport
      parentRoute: typeof AuthenticatedCadastroRoute
    }
    '/_authenticated/cadastro/servico': {
      id: '/_authenticated/cadastro/servico'
      path: '/servico'
      fullPath: '/cadastro/servico'
      preLoaderRoute: typeof AuthenticatedCadastroServicoRouteImport
      parentRoute: typeof AuthenticatedCadastroRoute
    }
    '/_authenticated/cadastro/colaboradores': {
      id: '/_authenticated/cadastro/colaboradores'
      path: '/colaboradores'
      fullPath: '/cadastro/colaboradores'
      preLoaderRoute: typeof AuthenticatedCadastroColaboradoresRouteImport
      parentRoute: typeof AuthenticatedCadastroRoute
    }
    '/_authenticated/cadastro/aviamentos': {
      id: '/_authenticated/cadastro/aviamentos'
      path: '/aviamentos'
      fullPath: '/cadastro/aviamentos'
      preLoaderRoute: typeof AuthenticatedCadastroAviamentosRouteImport
      parentRoute: typeof AuthenticatedCadastroRoute
    }
    '/_authenticated/cadastro/atributos': {
      id: '/_authenticated/cadastro/atributos'
      path: '/atributos'
      fullPath: '/cadastro/atributos'
      preLoaderRoute: typeof AuthenticatedCadastroAtributosRouteImport
      parentRoute: typeof AuthenticatedCadastroRoute
    }
    '/_authenticated/admin/usuarios-loja': {
      id: '/_authenticated/admin/usuarios-loja'
      path: '/usuarios-loja'
      fullPath: '/admin/usuarios-loja'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosLojaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/lojas': {
      id: '/_authenticated/admin/lojas'
      path: '/lojas'
      fullPath: '/admin/lojas'
      preLoaderRoute: typeof AuthenticatedAdminLojasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/identidade': {
      id: '/_authenticated/admin/identidade'
      path: '/identidade'
      fullPath: '/admin/identidade'
      preLoaderRoute: typeof AuthenticatedAdminIdentidadeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/producao/terceirizados/': {
      id: '/_authenticated/producao/terceirizados/'
      path: '/'
      fullPath: '/producao/terceirizados/'
      preLoaderRoute: typeof AuthenticatedProducaoTerceirizadosIndexRouteImport
      parentRoute: typeof AuthenticatedProducaoTerceirizadosRoute
    }
    '/_authenticated/producao/oficina/': {
      id: '/_authenticated/producao/oficina/'
      path: '/'
      fullPath: '/producao/oficina/'
      preLoaderRoute: typeof AuthenticatedProducaoOficinaIndexRouteImport
      parentRoute: typeof AuthenticatedProducaoOficinaRoute
    }
    '/_authenticated/producao/direcionamento/': {
      id: '/_authenticated/producao/direcionamento/'
      path: '/'
      fullPath: '/producao/direcionamento/'
      preLoaderRoute: typeof AuthenticatedProducaoDirecionamentoIndexRouteImport
      parentRoute: typeof AuthenticatedProducaoDirecionamentoRoute
    }
    '/_authenticated/producao/cq/': {
      id: '/_authenticated/producao/cq/'
      path: '/'
      fullPath: '/producao/cq/'
      preLoaderRoute: typeof AuthenticatedProducaoCqIndexRouteImport
      parentRoute: typeof AuthenticatedProducaoCqRoute
    }
    '/_authenticated/producao/cad/': {
      id: '/_authenticated/producao/cad/'
      path: '/'
      fullPath: '/producao/cad/'
      preLoaderRoute: typeof AuthenticatedProducaoCadIndexRouteImport
      parentRoute: typeof AuthenticatedProducaoCadRoute
    }
    '/_authenticated/producao/acabamento/': {
      id: '/_authenticated/producao/acabamento/'
      path: '/'
      fullPath: '/producao/acabamento/'
      preLoaderRoute: typeof AuthenticatedProducaoAcabamentoIndexRouteImport
      parentRoute: typeof AuthenticatedProducaoAcabamentoRoute
    }
    '/_authenticated/cadastro/tecidos/': {
      id: '/_authenticated/cadastro/tecidos/'
      path: '/'
      fullPath: '/cadastro/tecidos/'
      preLoaderRoute: typeof AuthenticatedCadastroTecidosIndexRouteImport
      parentRoute: typeof AuthenticatedCadastroTecidosRoute
    }
    '/_authenticated/producao/terceirizados/$modeloId': {
      id: '/_authenticated/producao/terceirizados/$modeloId'
      path: '/$modeloId'
      fullPath: '/producao/terceirizados/$modeloId'
      preLoaderRoute: typeof AuthenticatedProducaoTerceirizadosModeloIdRouteImport
      parentRoute: typeof AuthenticatedProducaoTerceirizadosRoute
    }
    '/_authenticated/producao/oficina/$modeloId': {
      id: '/_authenticated/producao/oficina/$modeloId'
      path: '/$modeloId'
      fullPath: '/producao/oficina/$modeloId'
      preLoaderRoute: typeof AuthenticatedProducaoOficinaModeloIdRouteImport
      parentRoute: typeof AuthenticatedProducaoOficinaRoute
    }
    '/_authenticated/producao/direcionamento/$modeloId': {
      id: '/_authenticated/producao/direcionamento/$modeloId'
      path: '/$modeloId'
      fullPath: '/producao/direcionamento/$modeloId'
      preLoaderRoute: typeof AuthenticatedProducaoDirecionamentoModeloIdRouteImport
      parentRoute: typeof AuthenticatedProducaoDirecionamentoRoute
    }
    '/_authenticated/producao/cq/$modeloId': {
      id: '/_authenticated/producao/cq/$modeloId'
      path: '/$modeloId'
      fullPath: '/producao/cq/$modeloId'
      preLoaderRoute: typeof AuthenticatedProducaoCqModeloIdRouteImport
      parentRoute: typeof AuthenticatedProducaoCqRoute
    }
    '/_authenticated/producao/cad/$modeloId': {
      id: '/_authenticated/producao/cad/$modeloId'
      path: '/$modeloId'
      fullPath: '/producao/cad/$modeloId'
      preLoaderRoute: typeof AuthenticatedProducaoCadModeloIdRouteImport
      parentRoute: typeof AuthenticatedProducaoCadRoute
    }
    '/_authenticated/producao/acabamento/$modeloId': {
      id: '/_authenticated/producao/acabamento/$modeloId'
      path: '/$modeloId'
      fullPath: '/producao/acabamento/$modeloId'
      preLoaderRoute: typeof AuthenticatedProducaoAcabamentoModeloIdRouteImport
      parentRoute: typeof AuthenticatedProducaoAcabamentoRoute
    }
    '/_authenticated/cadastro/tecidos/$artigoId': {
      id: '/_authenticated/cadastro/tecidos/$artigoId'
      path: '/$artigoId'
      fullPath: '/cadastro/tecidos/$artigoId'
      preLoaderRoute: typeof AuthenticatedCadastroTecidosArtigoIdRouteImport
      parentRoute: typeof AuthenticatedCadastroTecidosRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminIdentidadeRoute: typeof AuthenticatedAdminIdentidadeRoute
  AuthenticatedAdminLojasRoute: typeof AuthenticatedAdminLojasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminUsuariosLojaRoute: typeof AuthenticatedAdminUsuariosLojaRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
    AuthenticatedAdminIdentidadeRoute: AuthenticatedAdminIdentidadeRoute,
    AuthenticatedAdminLojasRoute: AuthenticatedAdminLojasRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminUsuariosLojaRoute: AuthenticatedAdminUsuariosLojaRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedCadastroTecidosRouteChildren {
  AuthenticatedCadastroTecidosArtigoIdRoute: typeof AuthenticatedCadastroTecidosArtigoIdRoute
  AuthenticatedCadastroTecidosIndexRoute: typeof AuthenticatedCadastroTecidosIndexRoute
}

const AuthenticatedCadastroTecidosRouteChildren: AuthenticatedCadastroTecidosRouteChildren =
  {
    AuthenticatedCadastroTecidosArtigoIdRoute:
      AuthenticatedCadastroTecidosArtigoIdRoute,
    AuthenticatedCadastroTecidosIndexRoute:
      AuthenticatedCadastroTecidosIndexRoute,
  }

const AuthenticatedCadastroTecidosRouteWithChildren =
  AuthenticatedCadastroTecidosRoute._addFileChildren(
    AuthenticatedCadastroTecidosRouteChildren,
  )

interface AuthenticatedCadastroRouteChildren {
  AuthenticatedCadastroAtributosRoute: typeof AuthenticatedCadastroAtributosRoute
  AuthenticatedCadastroAviamentosRoute: typeof AuthenticatedCadastroAviamentosRoute
  AuthenticatedCadastroColaboradoresRoute: typeof AuthenticatedCadastroColaboradoresRoute
  AuthenticatedCadastroServicoRoute: typeof AuthenticatedCadastroServicoRoute
  AuthenticatedCadastroTecidosRoute: typeof AuthenticatedCadastroTecidosRouteWithChildren
  AuthenticatedCadastroIndexRoute: typeof AuthenticatedCadastroIndexRoute
}

const AuthenticatedCadastroRouteChildren: AuthenticatedCadastroRouteChildren = {
  AuthenticatedCadastroAtributosRoute: AuthenticatedCadastroAtributosRoute,
  AuthenticatedCadastroAviamentosRoute: AuthenticatedCadastroAviamentosRoute,
  AuthenticatedCadastroColaboradoresRoute:
    AuthenticatedCadastroColaboradoresRoute,
  AuthenticatedCadastroServicoRoute: AuthenticatedCadastroServicoRoute,
  AuthenticatedCadastroTecidosRoute:
    AuthenticatedCadastroTecidosRouteWithChildren,
  AuthenticatedCadastroIndexRoute: AuthenticatedCadastroIndexRoute,
}

const AuthenticatedCadastroRouteWithChildren =
  AuthenticatedCadastroRoute._addFileChildren(
    AuthenticatedCadastroRouteChildren,
  )

interface AuthenticatedCriacaoRouteChildren {
  AuthenticatedCriacaoDesenvolvimentoRoute: typeof AuthenticatedCriacaoDesenvolvimentoRoute
  AuthenticatedCriacaoPlanejamentoRoute: typeof AuthenticatedCriacaoPlanejamentoRoute
  AuthenticatedCriacaoIndexRoute: typeof AuthenticatedCriacaoIndexRoute
}

const AuthenticatedCriacaoRouteChildren: AuthenticatedCriacaoRouteChildren = {
  AuthenticatedCriacaoDesenvolvimentoRoute:
    AuthenticatedCriacaoDesenvolvimentoRoute,
  AuthenticatedCriacaoPlanejamentoRoute: AuthenticatedCriacaoPlanejamentoRoute,
  AuthenticatedCriacaoIndexRoute: AuthenticatedCriacaoIndexRoute,
}

const AuthenticatedCriacaoRouteWithChildren =
  AuthenticatedCriacaoRoute._addFileChildren(AuthenticatedCriacaoRouteChildren)

interface AuthenticatedEntradaSaidaRouteChildren {
  AuthenticatedEntradaSaidaEstoqueRoute: typeof AuthenticatedEntradaSaidaEstoqueRoute
  AuthenticatedEntradaSaidaOcAviamentoRoute: typeof AuthenticatedEntradaSaidaOcAviamentoRoute
  AuthenticatedEntradaSaidaOcTecidoRoute: typeof AuthenticatedEntradaSaidaOcTecidoRoute
  AuthenticatedEntradaSaidaIndexRoute: typeof AuthenticatedEntradaSaidaIndexRoute
}

const AuthenticatedEntradaSaidaRouteChildren: AuthenticatedEntradaSaidaRouteChildren =
  {
    AuthenticatedEntradaSaidaEstoqueRoute:
      AuthenticatedEntradaSaidaEstoqueRoute,
    AuthenticatedEntradaSaidaOcAviamentoRoute:
      AuthenticatedEntradaSaidaOcAviamentoRoute,
    AuthenticatedEntradaSaidaOcTecidoRoute:
      AuthenticatedEntradaSaidaOcTecidoRoute,
    AuthenticatedEntradaSaidaIndexRoute: AuthenticatedEntradaSaidaIndexRoute,
  }

const AuthenticatedEntradaSaidaRouteWithChildren =
  AuthenticatedEntradaSaidaRoute._addFileChildren(
    AuthenticatedEntradaSaidaRouteChildren,
  )

interface AuthenticatedProducaoAcabamentoRouteChildren {
  AuthenticatedProducaoAcabamentoModeloIdRoute: typeof AuthenticatedProducaoAcabamentoModeloIdRoute
  AuthenticatedProducaoAcabamentoIndexRoute: typeof AuthenticatedProducaoAcabamentoIndexRoute
}

const AuthenticatedProducaoAcabamentoRouteChildren: AuthenticatedProducaoAcabamentoRouteChildren =
  {
    AuthenticatedProducaoAcabamentoModeloIdRoute:
      AuthenticatedProducaoAcabamentoModeloIdRoute,
    AuthenticatedProducaoAcabamentoIndexRoute:
      AuthenticatedProducaoAcabamentoIndexRoute,
  }

const AuthenticatedProducaoAcabamentoRouteWithChildren =
  AuthenticatedProducaoAcabamentoRoute._addFileChildren(
    AuthenticatedProducaoAcabamentoRouteChildren,
  )

interface AuthenticatedProducaoCadRouteChildren {
  AuthenticatedProducaoCadModeloIdRoute: typeof AuthenticatedProducaoCadModeloIdRoute
  AuthenticatedProducaoCadIndexRoute: typeof AuthenticatedProducaoCadIndexRoute
}

const AuthenticatedProducaoCadRouteChildren: AuthenticatedProducaoCadRouteChildren =
  {
    AuthenticatedProducaoCadModeloIdRoute:
      AuthenticatedProducaoCadModeloIdRoute,
    AuthenticatedProducaoCadIndexRoute: AuthenticatedProducaoCadIndexRoute,
  }

const AuthenticatedProducaoCadRouteWithChildren =
  AuthenticatedProducaoCadRoute._addFileChildren(
    AuthenticatedProducaoCadRouteChildren,
  )

interface AuthenticatedProducaoCqRouteChildren {
  AuthenticatedProducaoCqModeloIdRoute: typeof AuthenticatedProducaoCqModeloIdRoute
  AuthenticatedProducaoCqIndexRoute: typeof AuthenticatedProducaoCqIndexRoute
}

const AuthenticatedProducaoCqRouteChildren: AuthenticatedProducaoCqRouteChildren =
  {
    AuthenticatedProducaoCqModeloIdRoute: AuthenticatedProducaoCqModeloIdRoute,
    AuthenticatedProducaoCqIndexRoute: AuthenticatedProducaoCqIndexRoute,
  }

const AuthenticatedProducaoCqRouteWithChildren =
  AuthenticatedProducaoCqRoute._addFileChildren(
    AuthenticatedProducaoCqRouteChildren,
  )

interface AuthenticatedProducaoDirecionamentoRouteChildren {
  AuthenticatedProducaoDirecionamentoModeloIdRoute: typeof AuthenticatedProducaoDirecionamentoModeloIdRoute
  AuthenticatedProducaoDirecionamentoIndexRoute: typeof AuthenticatedProducaoDirecionamentoIndexRoute
}

const AuthenticatedProducaoDirecionamentoRouteChildren: AuthenticatedProducaoDirecionamentoRouteChildren =
  {
    AuthenticatedProducaoDirecionamentoModeloIdRoute:
      AuthenticatedProducaoDirecionamentoModeloIdRoute,
    AuthenticatedProducaoDirecionamentoIndexRoute:
      AuthenticatedProducaoDirecionamentoIndexRoute,
  }

const AuthenticatedProducaoDirecionamentoRouteWithChildren =
  AuthenticatedProducaoDirecionamentoRoute._addFileChildren(
    AuthenticatedProducaoDirecionamentoRouteChildren,
  )

interface AuthenticatedProducaoOficinaRouteChildren {
  AuthenticatedProducaoOficinaModeloIdRoute: typeof AuthenticatedProducaoOficinaModeloIdRoute
  AuthenticatedProducaoOficinaIndexRoute: typeof AuthenticatedProducaoOficinaIndexRoute
}

const AuthenticatedProducaoOficinaRouteChildren: AuthenticatedProducaoOficinaRouteChildren =
  {
    AuthenticatedProducaoOficinaModeloIdRoute:
      AuthenticatedProducaoOficinaModeloIdRoute,
    AuthenticatedProducaoOficinaIndexRoute:
      AuthenticatedProducaoOficinaIndexRoute,
  }

const AuthenticatedProducaoOficinaRouteWithChildren =
  AuthenticatedProducaoOficinaRoute._addFileChildren(
    AuthenticatedProducaoOficinaRouteChildren,
  )

interface AuthenticatedProducaoTerceirizadosRouteChildren {
  AuthenticatedProducaoTerceirizadosModeloIdRoute: typeof AuthenticatedProducaoTerceirizadosModeloIdRoute
  AuthenticatedProducaoTerceirizadosIndexRoute: typeof AuthenticatedProducaoTerceirizadosIndexRoute
}

const AuthenticatedProducaoTerceirizadosRouteChildren: AuthenticatedProducaoTerceirizadosRouteChildren =
  {
    AuthenticatedProducaoTerceirizadosModeloIdRoute:
      AuthenticatedProducaoTerceirizadosModeloIdRoute,
    AuthenticatedProducaoTerceirizadosIndexRoute:
      AuthenticatedProducaoTerceirizadosIndexRoute,
  }

const AuthenticatedProducaoTerceirizadosRouteWithChildren =
  AuthenticatedProducaoTerceirizadosRoute._addFileChildren(
    AuthenticatedProducaoTerceirizadosRouteChildren,
  )

interface AuthenticatedProducaoRouteChildren {
  AuthenticatedProducaoAcabamentoRoute: typeof AuthenticatedProducaoAcabamentoRouteWithChildren
  AuthenticatedProducaoCadRoute: typeof AuthenticatedProducaoCadRouteWithChildren
  AuthenticatedProducaoCqRoute: typeof AuthenticatedProducaoCqRouteWithChildren
  AuthenticatedProducaoDirecionamentoRoute: typeof AuthenticatedProducaoDirecionamentoRouteWithChildren
  AuthenticatedProducaoLancamentosRoute: typeof AuthenticatedProducaoLancamentosRoute
  AuthenticatedProducaoOficinaRoute: typeof AuthenticatedProducaoOficinaRouteWithChildren
  AuthenticatedProducaoTerceirizadosRoute: typeof AuthenticatedProducaoTerceirizadosRouteWithChildren
  AuthenticatedProducaoIndexRoute: typeof AuthenticatedProducaoIndexRoute
}

const AuthenticatedProducaoRouteChildren: AuthenticatedProducaoRouteChildren = {
  AuthenticatedProducaoAcabamentoRoute:
    AuthenticatedProducaoAcabamentoRouteWithChildren,
  AuthenticatedProducaoCadRoute: AuthenticatedProducaoCadRouteWithChildren,
  AuthenticatedProducaoCqRoute: AuthenticatedProducaoCqRouteWithChildren,
  AuthenticatedProducaoDirecionamentoRoute:
    AuthenticatedProducaoDirecionamentoRouteWithChildren,
  AuthenticatedProducaoLancamentosRoute: AuthenticatedProducaoLancamentosRoute,
  AuthenticatedProducaoOficinaRoute:
    AuthenticatedProducaoOficinaRouteWithChildren,
  AuthenticatedProducaoTerceirizadosRoute:
    AuthenticatedProducaoTerceirizadosRouteWithChildren,
  AuthenticatedProducaoIndexRoute: AuthenticatedProducaoIndexRoute,
}

const AuthenticatedProducaoRouteWithChildren =
  AuthenticatedProducaoRoute._addFileChildren(
    AuthenticatedProducaoRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCadastroRoute: typeof AuthenticatedCadastroRouteWithChildren
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCriacaoRoute: typeof AuthenticatedCriacaoRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEntradaSaidaRoute: typeof AuthenticatedEntradaSaidaRouteWithChildren
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedProducaoRoute: typeof AuthenticatedProducaoRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCadastroRoute: AuthenticatedCadastroRouteWithChildren,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCriacaoRoute: AuthenticatedCriacaoRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEntradaSaidaRoute: AuthenticatedEntradaSaidaRouteWithChildren,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedProducaoRoute: AuthenticatedProducaoRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
