/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPcpRouteImport } from './routes/_authenticated/pcp'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedExpedicaoRouteImport } from './routes/_authenticated/expedicao'
import { Route as AuthenticatedEntradaSaidaRouteImport } from './routes/_authenticated/entrada-saida'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCriacaoRouteImport } from './routes/_authenticated/criacao'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCadastroRouteImport } from './routes/_authenticated/cadastro'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedPcpIndexRouteImport } from './routes/_authenticated/pcp.index'
import { Route as AuthenticatedOtbIndexRouteImport } from './routes/_authenticated/otb.index'
import { Route as AuthenticatedExpedicaoIndexRouteImport } from './routes/_authenticated/expedicao.index'
import { Route as AuthenticatedEntradaSaidaIndexRouteImport } from './routes/_authenticated/entrada-saida.index'
import { Route as AuthenticatedCriacaoIndexRouteImport } from './routes/_authenticated/criacao.index'
import { Route as AuthenticatedCadastroIndexRouteImport } from './routes/_authenticated/cadastro.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedPcpServicosRouteImport } from './routes/_authenticated/pcp.servicos'
import { Route as AuthenticatedPcpOficinaRouteImport } from './routes/_authenticated/pcp.oficina'
import { Route as AuthenticatedPcpCadRouteImport } from './routes/_authenticated/pcp.cad'
import { Route as AuthenticatedExpedicaoLancamentosRouteImport } from './routes/_authenticated/expedicao.lancamentos'
import { Route as AuthenticatedExpedicaoDirecionamentoRouteImport } from './routes/_authenticated/expedicao.direcionamento'
import { Route as AuthenticatedExpedicaoCqRouteImport } from './routes/_authenticated/expedicao.cq'
import { Route as AuthenticatedEntradaSaidaOsTecidoRouteImport } from './routes/_authenticated/entrada-saida.os-tecido'
import { Route as AuthenticatedEntradaSaidaOsAviamentoRouteImport } from './routes/_authenticated/entrada-saida.os-aviamento'
import { Route as AuthenticatedEntradaSaidaOcTecidoRouteImport } from './routes/_authenticated/entrada-saida.oc-tecido'
import { Route as AuthenticatedEntradaSaidaOcPAcabadoRouteImport } from './routes/_authenticated/entrada-saida.oc-p-acabado'
import { Route as AuthenticatedEntradaSaidaOcInsumoRouteImport } from './routes/_authenticated/entrada-saida.oc-insumo'
import { Route as AuthenticatedEntradaSaidaOcAviamentoRouteImport } from './routes/_authenticated/entrada-saida.oc-aviamento'
import { Route as AuthenticatedEntradaSaidaExplosaoRouteImport } from './routes/_authenticated/entrada-saida.explosao'
import { Route as AuthenticatedEntradaSaidaAlertasTecidoRouteImport } from './routes/_authenticated/entrada-saida.alertas-tecido'
import { Route as AuthenticatedCriacaoProdutoAcabadoRouteImport } from './routes/_authenticated/criacao.produto-acabado'
import { Route as AuthenticatedCriacaoPlanejamentoRouteImport } from './routes/_authenticated/criacao.planejamento'
import { Route as AuthenticatedCriacaoPlanTecidoRouteImport } from './routes/_authenticated/criacao.plan-tecido'
import { Route as AuthenticatedCriacaoExplosaoRouteImport } from './routes/_authenticated/criacao.explosao'
import { Route as AuthenticatedCriacaoDesenvolvimentoRouteImport } from './routes/_authenticated/criacao.desenvolvimento'
import { Route as AuthenticatedCadastroTecidosRouteImport } from './routes/_authenticated/cadastro.tecidos'
import { Route as AuthenticatedCadastroServicoRouteImport } from './routes/_authenticated/cadastro.servico'
import { Route as AuthenticatedCadastroLojasRouteImport } from './routes/_authenticated/cadastro.lojas'
import { Route as AuthenticatedCadastroEtiquetasRouteImport } from './routes/_authenticated/cadastro.etiquetas'
import { Route as AuthenticatedCadastroDestinosRouteImport } from './routes/_authenticated/cadastro.destinos'
import { Route as AuthenticatedCadastroColaboradoresRouteImport } from './routes/_authenticated/cadastro.colaboradores'
import { Route as AuthenticatedCadastroAviamentosRouteImport } from './routes/_authenticated/cadastro.aviamentos'
import { Route as AuthenticatedCadastroAtributosRouteImport } from './routes/_authenticated/cadastro.atributos'
import { Route as AuthenticatedAdminUsuariosLojaRouteImport } from './routes/_authenticated/admin/usuarios-loja'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminLojasRouteImport } from './routes/_authenticated/admin/lojas'
import { Route as AuthenticatedAdminIdentidadeRouteImport } from './routes/_authenticated/admin/identidade'
import { Route as AuthenticatedAdminConfiguracoesRouteImport } from './routes/_authenticated/admin/configuracoes'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin/auditoria'
import { Route as AuthenticatedPcpServicosIndexRouteImport } from './routes/_authenticated/pcp.servicos.index'
import { Route as AuthenticatedPcpOficinaIndexRouteImport } from './routes/_authenticated/pcp.oficina.index'
import { Route as AuthenticatedPcpCadIndexRouteImport } from './routes/_authenticated/pcp.cad.index'
import { Route as AuthenticatedExpedicaoDirecionamentoIndexRouteImport } from './routes/_authenticated/expedicao.direcionamento.index'
import { Route as AuthenticatedExpedicaoCqIndexRouteImport } from './routes/_authenticated/expedicao.cq.index'
import { Route as AuthenticatedEntradaSaidaExplosaoIndexRouteImport } from './routes/_authenticated/entrada-saida.explosao.index'
import { Route as AuthenticatedCadastroTecidosIndexRouteImport } from './routes/_authenticated/cadastro.tecidos.index'
import { Route as AuthenticatedPcpServicosModeloIdRouteImport } from './routes/_authenticated/pcp.servicos.$modeloId'
import { Route as AuthenticatedPcpOficinaModeloIdRouteImport } from './routes/_authenticated/pcp.oficina.$modeloId'
import { Route as AuthenticatedPcpCadModeloIdRouteImport } from './routes/_authenticated/pcp.cad.$modeloId'
import { Route as AuthenticatedExpedicaoDirecionamentoModeloIdRouteImport } from './routes/_authenticated/expedicao.direcionamento.$modeloId'
import { Route as AuthenticatedExpedicaoCqModeloIdRouteImport } from './routes/_authenticated/expedicao.cq.$modeloId'
import { Route as AuthenticatedCadastroTecidosArtigoIdRouteImport } from './routes/_authenticated/cadastro.tecidos.$artigoId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPcpRoute = AuthenticatedPcpRouteImport.update({
  id: '/pcp',
  path: '/pcp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpedicaoRoute = AuthenticatedExpedicaoRouteImport.update({
  id: '/expedicao',
  path: '/expedicao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEntradaSaidaRoute =
  AuthenticatedEntradaSaidaRouteImport.update({
    id: '/entrada-saida',
    path: '/entrada-saida',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCriacaoRoute = AuthenticatedCriacaoRouteImport.update({
  id: '/criacao',
  path: '/criacao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastroRoute = AuthenticatedCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPcpIndexRoute = AuthenticatedPcpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPcpRoute,
} as any)
const AuthenticatedOtbIndexRoute = AuthenticatedOtbIndexRouteImport.update({
  id: '/otb/',
  path: '/otb/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExpedicaoIndexRoute =
  AuthenticatedExpedicaoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExpedicaoRoute,
  } as any)
const AuthenticatedEntradaSaidaIndexRoute =
  AuthenticatedEntradaSaidaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEntradaSaidaRoute,
  } as any)
const AuthenticatedCriacaoIndexRoute =
  AuthenticatedCriacaoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCriacaoRoute,
  } as any)
const AuthenticatedCadastroIndexRoute =
  AuthenticatedCadastroIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCadastroRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedPcpServicosRoute =
  AuthenticatedPcpServicosRouteImport.update({
    id: '/servicos',
    path: '/servicos',
    getParentRoute: () => AuthenticatedPcpRoute,
  } as any)
const AuthenticatedPcpOficinaRoute = AuthenticatedPcpOficinaRouteImport.update({
  id: '/oficina',
  path: '/oficina',
  getParentRoute: () => AuthenticatedPcpRoute,
} as any)
const AuthenticatedPcpCadRoute = AuthenticatedPcpCadRouteImport.update({
  id: '/cad',
  path: '/cad',
  getParentRoute: () => AuthenticatedPcpRoute,
} as any)
const AuthenticatedExpedicaoLancamentosRoute =
  AuthenticatedExpedicaoLancamentosRouteImport.update({
    id: '/lancamentos',
    path: '/lancamentos',
    getParentRoute: () => AuthenticatedExpedicaoRoute,
  } as any)
const AuthenticatedExpedicaoDirecionamentoRoute =
  AuthenticatedExpedicaoDirecionamentoRouteImport.update({
    id: '/direcionamento',
    path: '/direcionamento',
    getParentRoute: () => AuthenticatedExpedicaoRoute,
  } as any)
const AuthenticatedExpedicaoCqRoute =
  AuthenticatedExpedicaoCqRouteImport.update({
    id: '/cq',
    path: '/cq',
    getParentRoute: () => AuthenticatedExpedicaoRoute,
  } as any)
const AuthenticatedEntradaSaidaOsTecidoRoute =
  AuthenticatedEntradaSaidaOsTecidoRouteImport.update({
    id: '/os-tecido',
    path: '/os-tecido',
    getParentRoute: () => AuthenticatedEntradaSaidaRoute,
  } as any)
const AuthenticatedEntradaSaidaOsAviamentoRoute =
  AuthenticatedEntradaSaidaOsAviamentoRouteImport.update({
    id: '/os-aviamento',
    path: '/os-aviamento',
    getParentRoute: () => AuthenticatedEntradaSaidaRoute,
  } as any)
const AuthenticatedEntradaSaidaOcTecidoRoute =
  AuthenticatedEntradaSaidaOcTecidoRouteImport.update({
    id: '/oc-tecido',
    path: '/oc-tecido',
    getParentRoute: () => AuthenticatedEntradaSaidaRoute,
  } as any)
const AuthenticatedEntradaSaidaOcPAcabadoRoute =
  AuthenticatedEntradaSaidaOcPAcabadoRouteImport.update({
    id: '/oc-p-acabado',
    path: '/oc-p-acabado',
    getParentRoute: () => AuthenticatedEntradaSaidaRoute,
  } as any)
const AuthenticatedEntradaSaidaOcInsumoRoute =
  AuthenticatedEntradaSaidaOcInsumoRouteImport.update({
    id: '/oc-insumo',
    path: '/oc-insumo',
    getParentRoute: () => AuthenticatedEntradaSaidaRoute,
  } as any)
const AuthenticatedEntradaSaidaOcAviamentoRoute =
  AuthenticatedEntradaSaidaOcAviamentoRouteImport.update({
    id: '/oc-aviamento',
    path: '/oc-aviamento',
    getParentRoute: () => AuthenticatedEntradaSaidaRoute,
  } as any)
const AuthenticatedEntradaSaidaExplosaoRoute =
  AuthenticatedEntradaSaidaExplosaoRouteImport.update({
    id: '/explosao',
    path: '/explosao',
    getParentRoute: () => AuthenticatedEntradaSaidaRoute,
  } as any)
const AuthenticatedEntradaSaidaAlertasTecidoRoute =
  AuthenticatedEntradaSaidaAlertasTecidoRouteImport.update({
    id: '/alertas-tecido',
    path: '/alertas-tecido',
    getParentRoute: () => AuthenticatedEntradaSaidaRoute,
  } as any)
const AuthenticatedCriacaoProdutoAcabadoRoute =
  AuthenticatedCriacaoProdutoAcabadoRouteImport.update({
    id: '/produto-acabado',
    path: '/produto-acabado',
    getParentRoute: () => AuthenticatedCriacaoRoute,
  } as any)
const AuthenticatedCriacaoPlanejamentoRoute =
  AuthenticatedCriacaoPlanejamentoRouteImport.update({
    id: '/planejamento',
    path: '/planejamento',
    getParentRoute: () => AuthenticatedCriacaoRoute,
  } as any)
const AuthenticatedCriacaoPlanTecidoRoute =
  AuthenticatedCriacaoPlanTecidoRouteImport.update({
    id: '/plan-tecido',
    path: '/plan-tecido',
    getParentRoute: () => AuthenticatedCriacaoRoute,
  } as any)
const AuthenticatedCriacaoExplosaoRoute =
  AuthenticatedCriacaoExplosaoRouteImport.update({
    id: '/explosao',
    path: '/explosao',
    getParentRoute: () => AuthenticatedCriacaoRoute,
  } as any)
const AuthenticatedCriacaoDesenvolvimentoRoute =
  AuthenticatedCriacaoDesenvolvimentoRouteImport.update({
    id: '/desenvolvimento',
    path: '/desenvolvimento',
    getParentRoute: () => AuthenticatedCriacaoRoute,
  } as any)
const AuthenticatedCadastroTecidosRoute =
  AuthenticatedCadastroTecidosRouteImport.update({
    id: '/tecidos',
    path: '/tecidos',
    getParentRoute: () => AuthenticatedCadastroRoute,
  } as any)
const AuthenticatedCadastroServicoRoute =
  AuthenticatedCadastroServicoRouteImport.update({
    id: '/servico',
    path: '/servico',
    getParentRoute: () => AuthenticatedCadastroRoute,
  } as any)
const AuthenticatedCadastroLojasRoute =
  AuthenticatedCadastroLojasRouteImport.update({
    id: '/lojas',
    path: '/lojas',
    getParentRoute: () => AuthenticatedCadastroRoute,
  } as any)
const AuthenticatedCadastroEtiquetasRoute =
  AuthenticatedCadastroEtiquetasRouteImport.update({
    id: '/etiquetas',
    path: '/etiquetas',
    getParentRoute: () => AuthenticatedCadastroRoute,
  } as any)
const AuthenticatedCadastroDestinosRoute =
  AuthenticatedCadastroDestinosRouteImport.update({
    id: '/destinos',
    path: '/destinos',
    getParentRoute: () => AuthenticatedCadastroRoute,
  } as any)
const AuthenticatedCadastroColaboradoresRoute =
  AuthenticatedCadastroColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedCadastroRoute,
  } as any)
const AuthenticatedCadastroAviamentosRoute =
  AuthenticatedCadastroAviamentosRouteImport.update({
    id: '/aviamentos',
    path: '/aviamentos',
    getParentRoute: () => AuthenticatedCadastroRoute,
  } as any)
const AuthenticatedCadastroAtributosRoute =
  AuthenticatedCadastroAtributosRouteImport.update({
    id: '/atributos',
    path: '/atributos',
    getParentRoute: () => AuthenticatedCadastroRoute,
  } as any)
const AuthenticatedAdminUsuariosLojaRoute =
  AuthenticatedAdminUsuariosLojaRouteImport.update({
    id: '/usuarios-loja',
    path: '/usuarios-loja',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLojasRoute = AuthenticatedAdminLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminIdentidadeRoute =
  AuthenticatedAdminIdentidadeRouteImport.update({
    id: '/identidade',
    path: '/identidade',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfiguracoesRoute =
  AuthenticatedAdminConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedPcpServicosIndexRoute =
  AuthenticatedPcpServicosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPcpServicosRoute,
  } as any)
const AuthenticatedPcpOficinaIndexRoute =
  AuthenticatedPcpOficinaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPcpOficinaRoute,
  } as any)
const AuthenticatedPcpCadIndexRoute =
  AuthenticatedPcpCadIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPcpCadRoute,
  } as any)
const AuthenticatedExpedicaoDirecionamentoIndexRoute =
  AuthenticatedExpedicaoDirecionamentoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExpedicaoDirecionamentoRoute,
  } as any)
const AuthenticatedExpedicaoCqIndexRoute =
  AuthenticatedExpedicaoCqIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExpedicaoCqRoute,
  } as any)
const AuthenticatedEntradaSaidaExplosaoIndexRoute =
  AuthenticatedEntradaSaidaExplosaoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEntradaSaidaExplosaoRoute,
  } as any)
const AuthenticatedCadastroTecidosIndexRoute =
  AuthenticatedCadastroTecidosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCadastroTecidosRoute,
  } as any)
const AuthenticatedPcpServicosModeloIdRoute =
  AuthenticatedPcpServicosModeloIdRouteImport.update({
    id: '/$modeloId',
    path: '/$modeloId',
    getParentRoute: () => AuthenticatedPcpServicosRoute,
  } as any)
const AuthenticatedPcpOficinaModeloIdRoute =
  AuthenticatedPcpOficinaModeloIdRouteImport.update({
    id: '/$modeloId',
    path: '/$modeloId',
    getParentRoute: () => AuthenticatedPcpOficinaRoute,
  } as any)
const AuthenticatedPcpCadModeloIdRoute =
  AuthenticatedPcpCadModeloIdRouteImport.update({
    id: '/$modeloId',
    path: '/$modeloId',
    getParentRoute: () => AuthenticatedPcpCadRoute,
  } as any)
const AuthenticatedExpedicaoDirecionamentoModeloIdRoute =
  AuthenticatedExpedicaoDirecionamentoModeloIdRouteImport.update({
    id: '/$modeloId',
    path: '/$modeloId',
    getParentRoute: () => AuthenticatedExpedicaoDirecionamentoRoute,
  } as any)
const AuthenticatedExpedicaoCqModeloIdRoute =
  AuthenticatedExpedicaoCqModeloIdRouteImport.update({
    id: '/$modeloId',
    path: '/$modeloId',
    getParentRoute: () => AuthenticatedExpedicaoCqRoute,
  } as any)
const AuthenticatedCadastroTecidosArtigoIdRoute =
  AuthenticatedCadastroTecidosArtigoIdRouteImport.update({
    id: '/$artigoId',
    path: '/$artigoId',
    getParentRoute: () => AuthenticatedCadastroTecidosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/cadastro': typeof AuthenticatedCadastroRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/criacao': typeof AuthenticatedCriacaoRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entrada-saida': typeof AuthenticatedEntradaSaidaRouteWithChildren
  '/expedicao': typeof AuthenticatedExpedicaoRouteWithChildren
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/home': typeof AuthenticatedHomeRoute
  '/pcp': typeof AuthenticatedPcpRouteWithChildren
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/identidade': typeof AuthenticatedAdminIdentidadeRoute
  '/admin/lojas': typeof AuthenticatedAdminLojasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/usuarios-loja': typeof AuthenticatedAdminUsuariosLojaRoute
  '/cadastro/atributos': typeof AuthenticatedCadastroAtributosRoute
  '/cadastro/aviamentos': typeof AuthenticatedCadastroAviamentosRoute
  '/cadastro/colaboradores': typeof AuthenticatedCadastroColaboradoresRoute
  '/cadastro/destinos': typeof AuthenticatedCadastroDestinosRoute
  '/cadastro/etiquetas': typeof AuthenticatedCadastroEtiquetasRoute
  '/cadastro/lojas': typeof AuthenticatedCadastroLojasRoute
  '/cadastro/servico': typeof AuthenticatedCadastroServicoRoute
  '/cadastro/tecidos': typeof AuthenticatedCadastroTecidosRouteWithChildren
  '/criacao/desenvolvimento': typeof AuthenticatedCriacaoDesenvolvimentoRoute
  '/criacao/explosao': typeof AuthenticatedCriacaoExplosaoRoute
  '/criacao/plan-tecido': typeof AuthenticatedCriacaoPlanTecidoRoute
  '/criacao/planejamento': typeof AuthenticatedCriacaoPlanejamentoRoute
  '/criacao/produto-acabado': typeof AuthenticatedCriacaoProdutoAcabadoRoute
  '/entrada-saida/alertas-tecido': typeof AuthenticatedEntradaSaidaAlertasTecidoRoute
  '/entrada-saida/explosao': typeof AuthenticatedEntradaSaidaExplosaoRouteWithChildren
  '/entrada-saida/oc-aviamento': typeof AuthenticatedEntradaSaidaOcAviamentoRoute
  '/entrada-saida/oc-insumo': typeof AuthenticatedEntradaSaidaOcInsumoRoute
  '/entrada-saida/oc-p-acabado': typeof AuthenticatedEntradaSaidaOcPAcabadoRoute
  '/entrada-saida/oc-tecido': typeof AuthenticatedEntradaSaidaOcTecidoRoute
  '/entrada-saida/os-aviamento': typeof AuthenticatedEntradaSaidaOsAviamentoRoute
  '/entrada-saida/os-tecido': typeof AuthenticatedEntradaSaidaOsTecidoRoute
  '/expedicao/cq': typeof AuthenticatedExpedicaoCqRouteWithChildren
  '/expedicao/direcionamento': typeof AuthenticatedExpedicaoDirecionamentoRouteWithChildren
  '/expedicao/lancamentos': typeof AuthenticatedExpedicaoLancamentosRoute
  '/pcp/cad': typeof AuthenticatedPcpCadRouteWithChildren
  '/pcp/oficina': typeof AuthenticatedPcpOficinaRouteWithChildren
  '/pcp/servicos': typeof AuthenticatedPcpServicosRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/cadastro/': typeof AuthenticatedCadastroIndexRoute
  '/criacao/': typeof AuthenticatedCriacaoIndexRoute
  '/entrada-saida/': typeof AuthenticatedEntradaSaidaIndexRoute
  '/expedicao/': typeof AuthenticatedExpedicaoIndexRoute
  '/otb/': typeof AuthenticatedOtbIndexRoute
  '/pcp/': typeof AuthenticatedPcpIndexRoute
  '/cadastro/tecidos/$artigoId': typeof AuthenticatedCadastroTecidosArtigoIdRoute
  '/expedicao/cq/$modeloId': typeof AuthenticatedExpedicaoCqModeloIdRoute
  '/expedicao/direcionamento/$modeloId': typeof AuthenticatedExpedicaoDirecionamentoModeloIdRoute
  '/pcp/cad/$modeloId': typeof AuthenticatedPcpCadModeloIdRoute
  '/pcp/oficina/$modeloId': typeof AuthenticatedPcpOficinaModeloIdRoute
  '/pcp/servicos/$modeloId': typeof AuthenticatedPcpServicosModeloIdRoute
  '/cadastro/tecidos/': typeof AuthenticatedCadastroTecidosIndexRoute
  '/entrada-saida/explosao/': typeof AuthenticatedEntradaSaidaExplosaoIndexRoute
  '/expedicao/cq/': typeof AuthenticatedExpedicaoCqIndexRoute
  '/expedicao/direcionamento/': typeof AuthenticatedExpedicaoDirecionamentoIndexRoute
  '/pcp/cad/': typeof AuthenticatedPcpCadIndexRoute
  '/pcp/oficina/': typeof AuthenticatedPcpOficinaIndexRoute
  '/pcp/servicos/': typeof AuthenticatedPcpServicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/home': typeof AuthenticatedHomeRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/admin/identidade': typeof AuthenticatedAdminIdentidadeRoute
  '/admin/lojas': typeof AuthenticatedAdminLojasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/usuarios-loja': typeof AuthenticatedAdminUsuariosLojaRoute
  '/cadastro/atributos': typeof AuthenticatedCadastroAtributosRoute
  '/cadastro/aviamentos': typeof AuthenticatedCadastroAviamentosRoute
  '/cadastro/colaboradores': typeof AuthenticatedCadastroColaboradoresRoute
  '/cadastro/destinos': typeof AuthenticatedCadastroDestinosRoute
  '/cadastro/etiquetas': typeof AuthenticatedCadastroEtiquetasRoute
  '/cadastro/lojas': typeof AuthenticatedCadastroLojasRoute
  '/cadastro/servico': typeof AuthenticatedCadastroServicoRoute
  '/criacao/desenvolvimento': typeof AuthenticatedCriacaoDesenvolvimentoRoute
  '/criacao/explosao': typeof AuthenticatedCriacaoExplosaoRoute
  '/criacao/plan-tecido': typeof AuthenticatedCriacaoPlanTecidoRoute
  '/criacao/planejamento': typeof AuthenticatedCriacaoPlanejamentoRoute
  '/criacao/produto-acabado': typeof AuthenticatedCriacaoProdutoAcabadoRoute
  '/entrada-saida/alertas-tecido': typeof AuthenticatedEntradaSaidaAlertasTecidoRoute
  '/entrada-saida/oc-aviamento': typeof AuthenticatedEntradaSaidaOcAviamentoRoute
  '/entrada-saida/oc-insumo': typeof AuthenticatedEntradaSaidaOcInsumoRoute
  '/entrada-saida/oc-p-acabado': typeof AuthenticatedEntradaSaidaOcPAcabadoRoute
  '/entrada-saida/oc-tecido': typeof AuthenticatedEntradaSaidaOcTecidoRoute
  '/entrada-saida/os-aviamento': typeof AuthenticatedEntradaSaidaOsAviamentoRoute
  '/entrada-saida/os-tecido': typeof AuthenticatedEntradaSaidaOsTecidoRoute
  '/expedicao/lancamentos': typeof AuthenticatedExpedicaoLancamentosRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/cadastro': typeof AuthenticatedCadastroIndexRoute
  '/criacao': typeof AuthenticatedCriacaoIndexRoute
  '/entrada-saida': typeof AuthenticatedEntradaSaidaIndexRoute
  '/expedicao': typeof AuthenticatedExpedicaoIndexRoute
  '/otb': typeof AuthenticatedOtbIndexRoute
  '/pcp': typeof AuthenticatedPcpIndexRoute
  '/cadastro/tecidos/$artigoId': typeof AuthenticatedCadastroTecidosArtigoIdRoute
  '/expedicao/cq/$modeloId': typeof AuthenticatedExpedicaoCqModeloIdRoute
  '/expedicao/direcionamento/$modeloId': typeof AuthenticatedExpedicaoDirecionamentoModeloIdRoute
  '/pcp/cad/$modeloId': typeof AuthenticatedPcpCadModeloIdRoute
  '/pcp/oficina/$modeloId': typeof AuthenticatedPcpOficinaModeloIdRoute
  '/pcp/servicos/$modeloId': typeof AuthenticatedPcpServicosModeloIdRoute
  '/cadastro/tecidos': typeof AuthenticatedCadastroTecidosIndexRoute
  '/entrada-saida/explosao': typeof AuthenticatedEntradaSaidaExplosaoIndexRoute
  '/expedicao/cq': typeof AuthenticatedExpedicaoCqIndexRoute
  '/expedicao/direcionamento': typeof AuthenticatedExpedicaoDirecionamentoIndexRoute
  '/pcp/cad': typeof AuthenticatedPcpCadIndexRoute
  '/pcp/oficina': typeof AuthenticatedPcpOficinaIndexRoute
  '/pcp/servicos': typeof AuthenticatedPcpServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/cadastro': typeof AuthenticatedCadastroRouteWithChildren
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/criacao': typeof AuthenticatedCriacaoRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/entrada-saida': typeof AuthenticatedEntradaSaidaRouteWithChildren
  '/_authenticated/expedicao': typeof AuthenticatedExpedicaoRouteWithChildren
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/pcp': typeof AuthenticatedPcpRouteWithChildren
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/configuracoes': typeof AuthenticatedAdminConfiguracoesRoute
  '/_authenticated/admin/identidade': typeof AuthenticatedAdminIdentidadeRoute
  '/_authenticated/admin/lojas': typeof AuthenticatedAdminLojasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/usuarios-loja': typeof AuthenticatedAdminUsuariosLojaRoute
  '/_authenticated/cadastro/atributos': typeof AuthenticatedCadastroAtributosRoute
  '/_authenticated/cadastro/aviamentos': typeof AuthenticatedCadastroAviamentosRoute
  '/_authenticated/cadastro/colaboradores': typeof AuthenticatedCadastroColaboradoresRoute
  '/_authenticated/cadastro/destinos': typeof AuthenticatedCadastroDestinosRoute
  '/_authenticated/cadastro/etiquetas': typeof AuthenticatedCadastroEtiquetasRoute
  '/_authenticated/cadastro/lojas': typeof AuthenticatedCadastroLojasRoute
  '/_authenticated/cadastro/servico': typeof AuthenticatedCadastroServicoRoute
  '/_authenticated/cadastro/tecidos': typeof AuthenticatedCadastroTecidosRouteWithChildren
  '/_authenticated/criacao/desenvolvimento': typeof AuthenticatedCriacaoDesenvolvimentoRoute
  '/_authenticated/criacao/explosao': typeof AuthenticatedCriacaoExplosaoRoute
  '/_authenticated/criacao/plan-tecido': typeof AuthenticatedCriacaoPlanTecidoRoute
  '/_authenticated/criacao/planejamento': typeof AuthenticatedCriacaoPlanejamentoRoute
  '/_authenticated/criacao/produto-acabado': typeof AuthenticatedCriacaoProdutoAcabadoRoute
  '/_authenticated/entrada-saida/alertas-tecido': typeof AuthenticatedEntradaSaidaAlertasTecidoRoute
  '/_authenticated/entrada-saida/explosao': typeof AuthenticatedEntradaSaidaExplosaoRouteWithChildren
  '/_authenticated/entrada-saida/oc-aviamento': typeof AuthenticatedEntradaSaidaOcAviamentoRoute
  '/_authenticated/entrada-saida/oc-insumo': typeof AuthenticatedEntradaSaidaOcInsumoRoute
  '/_authenticated/entrada-saida/oc-p-acabado': typeof AuthenticatedEntradaSaidaOcPAcabadoRoute
  '/_authenticated/entrada-saida/oc-tecido': typeof AuthenticatedEntradaSaidaOcTecidoRoute
  '/_authenticated/entrada-saida/os-aviamento': typeof AuthenticatedEntradaSaidaOsAviamentoRoute
  '/_authenticated/entrada-saida/os-tecido': typeof AuthenticatedEntradaSaidaOsTecidoRoute
  '/_authenticated/expedicao/cq': typeof AuthenticatedExpedicaoCqRouteWithChildren
  '/_authenticated/expedicao/direcionamento': typeof AuthenticatedExpedicaoDirecionamentoRouteWithChildren
  '/_authenticated/expedicao/lancamentos': typeof AuthenticatedExpedicaoLancamentosRoute
  '/_authenticated/pcp/cad': typeof AuthenticatedPcpCadRouteWithChildren
  '/_authenticated/pcp/oficina': typeof AuthenticatedPcpOficinaRouteWithChildren
  '/_authenticated/pcp/servicos': typeof AuthenticatedPcpServicosRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/cadastro/': typeof AuthenticatedCadastroIndexRoute
  '/_authenticated/criacao/': typeof AuthenticatedCriacaoIndexRoute
  '/_authenticated/entrada-saida/': typeof AuthenticatedEntradaSaidaIndexRoute
  '/_authenticated/expedicao/': typeof AuthenticatedExpedicaoIndexRoute
  '/_authenticated/otb/': typeof AuthenticatedOtbIndexRoute
  '/_authenticated/pcp/': typeof AuthenticatedPcpIndexRoute
  '/_authenticated/cadastro/tecidos/$artigoId': typeof AuthenticatedCadastroTecidosArtigoIdRoute
  '/_authenticated/expedicao/cq/$modeloId': typeof AuthenticatedExpedicaoCqModeloIdRoute
  '/_authenticated/expedicao/direcionamento/$modeloId': typeof AuthenticatedExpedicaoDirecionamentoModeloIdRoute
  '/_authenticated/pcp/cad/$modeloId': typeof AuthenticatedPcpCadModeloIdRoute
  '/_authenticated/pcp/oficina/$modeloId': typeof AuthenticatedPcpOficinaModeloIdRoute
  '/_authenticated/pcp/servicos/$modeloId': typeof AuthenticatedPcpServicosModeloIdRoute
  '/_authenticated/cadastro/tecidos/': typeof AuthenticatedCadastroTecidosIndexRoute
  '/_authenticated/entrada-saida/explosao/': typeof AuthenticatedEntradaSaidaExplosaoIndexRoute
  '/_authenticated/expedicao/cq/': typeof AuthenticatedExpedicaoCqIndexRoute
  '/_authenticated/expedicao/direcionamento/': typeof AuthenticatedExpedicaoDirecionamentoIndexRoute
  '/_authenticated/pcp/cad/': typeof AuthenticatedPcpCadIndexRoute
  '/_authenticated/pcp/oficina/': typeof AuthenticatedPcpOficinaIndexRoute
  '/_authenticated/pcp/servicos/': typeof AuthenticatedPcpServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/cadastro'
    | '/configuracoes'
    | '/criacao'
    | '/dashboard'
    | '/entrada-saida'
    | '/expedicao'
    | '/financeiro'
    | '/home'
    | '/pcp'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/identidade'
    | '/admin/lojas'
    | '/admin/usuarios'
    | '/admin/usuarios-loja'
    | '/cadastro/atributos'
    | '/cadastro/aviamentos'
    | '/cadastro/colaboradores'
    | '/cadastro/destinos'
    | '/cadastro/etiquetas'
    | '/cadastro/lojas'
    | '/cadastro/servico'
    | '/cadastro/tecidos'
    | '/criacao/desenvolvimento'
    | '/criacao/explosao'
    | '/criacao/plan-tecido'
    | '/criacao/planejamento'
    | '/criacao/produto-acabado'
    | '/entrada-saida/alertas-tecido'
    | '/entrada-saida/explosao'
    | '/entrada-saida/oc-aviamento'
    | '/entrada-saida/oc-insumo'
    | '/entrada-saida/oc-p-acabado'
    | '/entrada-saida/oc-tecido'
    | '/entrada-saida/os-aviamento'
    | '/entrada-saida/os-tecido'
    | '/expedicao/cq'
    | '/expedicao/direcionamento'
    | '/expedicao/lancamentos'
    | '/pcp/cad'
    | '/pcp/oficina'
    | '/pcp/servicos'
    | '/admin/'
    | '/cadastro/'
    | '/criacao/'
    | '/entrada-saida/'
    | '/expedicao/'
    | '/otb/'
    | '/pcp/'
    | '/cadastro/tecidos/$artigoId'
    | '/expedicao/cq/$modeloId'
    | '/expedicao/direcionamento/$modeloId'
    | '/pcp/cad/$modeloId'
    | '/pcp/oficina/$modeloId'
    | '/pcp/servicos/$modeloId'
    | '/cadastro/tecidos/'
    | '/entrada-saida/explosao/'
    | '/expedicao/cq/'
    | '/expedicao/direcionamento/'
    | '/pcp/cad/'
    | '/pcp/oficina/'
    | '/pcp/servicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/home'
    | '/admin/auditoria'
    | '/admin/configuracoes'
    | '/admin/identidade'
    | '/admin/lojas'
    | '/admin/usuarios'
    | '/admin/usuarios-loja'
    | '/cadastro/atributos'
    | '/cadastro/aviamentos'
    | '/cadastro/colaboradores'
    | '/cadastro/destinos'
    | '/cadastro/etiquetas'
    | '/cadastro/lojas'
    | '/cadastro/servico'
    | '/criacao/desenvolvimento'
    | '/criacao/explosao'
    | '/criacao/plan-tecido'
    | '/criacao/planejamento'
    | '/criacao/produto-acabado'
    | '/entrada-saida/alertas-tecido'
    | '/entrada-saida/oc-aviamento'
    | '/entrada-saida/oc-insumo'
    | '/entrada-saida/oc-p-acabado'
    | '/entrada-saida/oc-tecido'
    | '/entrada-saida/os-aviamento'
    | '/entrada-saida/os-tecido'
    | '/expedicao/lancamentos'
    | '/admin'
    | '/cadastro'
    | '/criacao'
    | '/entrada-saida'
    | '/expedicao'
    | '/otb'
    | '/pcp'
    | '/cadastro/tecidos/$artigoId'
    | '/expedicao/cq/$modeloId'
    | '/expedicao/direcionamento/$modeloId'
    | '/pcp/cad/$modeloId'
    | '/pcp/oficina/$modeloId'
    | '/pcp/servicos/$modeloId'
    | '/cadastro/tecidos'
    | '/entrada-saida/explosao'
    | '/expedicao/cq'
    | '/expedicao/direcionamento'
    | '/pcp/cad'
    | '/pcp/oficina'
    | '/pcp/servicos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/cadastro'
    | '/_authenticated/configuracoes'
    | '/_authenticated/criacao'
    | '/_authenticated/dashboard'
    | '/_authenticated/entrada-saida'
    | '/_authenticated/expedicao'
    | '/_authenticated/financeiro'
    | '/_authenticated/home'
    | '/_authenticated/pcp'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/configuracoes'
    | '/_authenticated/admin/identidade'
    | '/_authenticated/admin/lojas'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/usuarios-loja'
    | '/_authenticated/cadastro/atributos'
    | '/_authenticated/cadastro/aviamentos'
    | '/_authenticated/cadastro/colaboradores'
    | '/_authenticated/cadastro/destinos'
    | '/_authenticated/cadastro/etiquetas'
    | '/_authenticated/cadastro/lojas'
    | '/_authenticated/cadastro/servico'
    | '/_authenticated/cadastro/tecidos'
    | '/_authenticated/criacao/desenvolvimento'
    | '/_authenticated/criacao/explosao'
    | '/_authenticated/criacao/plan-tecido'
    | '/_authenticated/criacao/planejamento'
    | '/_authenticated/criacao/produto-acabado'
    | '/_authenticated/entrada-saida/alertas-tecido'
    | '/_authenticated/entrada-saida/explosao'
    | '/_authenticated/entrada-saida/oc-aviamento'
    | '/_authenticated/entrada-saida/oc-insumo'
    | '/_authenticated/entrada-saida/oc-p-acabado'
    | '/_authenticated/entrada-saida/oc-tecido'
    | '/_authenticated/entrada-saida/os-aviamento'
    | '/_authenticated/entrada-saida/os-tecido'
    | '/_authenticated/expedicao/cq'
    | '/_authenticated/expedicao/direcionamento'
    | '/_authenticated/expedicao/lancamentos'
    | '/_authenticated/pcp/cad'
    | '/_authenticated/pcp/oficina'
    | '/_authenticated/pcp/servicos'
    | '/_authenticated/admin/'
    | '/_authenticated/cadastro/'
    | '/_authenticated/criacao/'
    | '/_authenticated/entrada-saida/'
    | '/_authenticated/expedicao/'
    | '/_authenticated/otb/'
    | '/_authenticated/pcp/'
    | '/_authenticated/cadastro/tecidos/$artigoId'
    | '/_authenticated/expedicao/cq/$modeloId'
    | '/_authenticated/expedicao/direcionamento/$modeloId'
    | '/_authenticated/pcp/cad/$modeloId'
    | '/_authenticated/pcp/oficina/$modeloId'
    | '/_authenticated/pcp/servicos/$modeloId'
    | '/_authenticated/cadastro/tecidos/'
    | '/_authenticated/entrada-saida/explosao/'
    | '/_authenticated/expedicao/cq/'
    | '/_authenticated/expedicao/direcionamento/'
    | '/_authenticated/pcp/cad/'
    | '/_authenticated/pcp/oficina/'
    | '/_authenticated/pcp/servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pcp': {
      id: '/_authenticated/pcp'
      path: '/pcp'
      fullPath: '/pcp'
      preLoaderRoute: typeof AuthenticatedPcpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expedicao': {
      id: '/_authenticated/expedicao'
      path: '/expedicao'
      fullPath: '/expedicao'
      preLoaderRoute: typeof AuthenticatedExpedicaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entrada-saida': {
      id: '/_authenticated/entrada-saida'
      path: '/entrada-saida'
      fullPath: '/entrada-saida'
      preLoaderRoute: typeof AuthenticatedEntradaSaidaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/criacao': {
      id: '/_authenticated/criacao'
      path: '/criacao'
      fullPath: '/criacao'
      preLoaderRoute: typeof AuthenticatedCriacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro': {
      id: '/_authenticated/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof AuthenticatedCadastroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pcp/': {
      id: '/_authenticated/pcp/'
      path: '/'
      fullPath: '/pcp/'
      preLoaderRoute: typeof AuthenticatedPcpIndexRouteImport
      parentRoute: typeof AuthenticatedPcpRoute
    }
    '/_authenticated/otb/': {
      id: '/_authenticated/otb/'
      path: '/otb'
      fullPath: '/otb/'
      preLoaderRoute: typeof AuthenticatedOtbIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expedicao/': {
      id: '/_authenticated/expedicao/'
      path: '/'
      fullPath: '/expedicao/'
      preLoaderRoute: typeof AuthenticatedExpedicaoIndexRouteImport
      parentRoute: typeof AuthenticatedExpedicaoRoute
    }
    '/_authenticated/entrada-saida/': {
      id: '/_authenticated/entrada-saida/'
      path: '/'
      fullPath: '/entrada-saida/'
      preLoaderRoute: typeof AuthenticatedEntradaSaidaIndexRouteImport
      parentRoute: typeof AuthenticatedEntradaSaidaRoute
    }
    '/_authenticated/criacao/': {
      id: '/_authenticated/criacao/'
      path: '/'
      fullPath: '/criacao/'
      preLoaderRoute: typeof AuthenticatedCriacaoIndexRouteImport
      parentRoute: typeof AuthenticatedCriacaoRoute
    }
    '/_authenticated/cadastro/': {
      id: '/_authenticated/cadastro/'
      path: '/'
      fullPath: '/cadastro/'
      preLoaderRoute: typeof AuthenticatedCadastroIndexRouteImport
      parentRoute: typeof AuthenticatedCadastroRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/pcp/servicos': {
      id: '/_authenticated/pcp/servicos'
      path: '/servicos'
      fullPath: '/pcp/servicos'
      preLoaderRoute: typeof AuthenticatedPcpServicosRouteImport
      parentRoute: typeof AuthenticatedPcpRoute
    }
    '/_authenticated/pcp/oficina': {
      id: '/_authenticated/pcp/oficina'
      path: '/oficina'
      fullPath: '/pcp/oficina'
      preLoaderRoute: typeof AuthenticatedPcpOficinaRouteImport
      parentRoute: typeof AuthenticatedPcpRoute
    }
    '/_authenticated/pcp/cad': {
      id: '/_authenticated/pcp/cad'
      path: '/cad'
      fullPath: '/pcp/cad'
      preLoaderRoute: typeof AuthenticatedPcpCadRouteImport
      parentRoute: typeof AuthenticatedPcpRoute
    }
    '/_authenticated/expedicao/lancamentos': {
      id: '/_authenticated/expedicao/lancamentos'
      path: '/lancamentos'
      fullPath: '/expedicao/lancamentos'
      preLoaderRoute: typeof AuthenticatedExpedicaoLancamentosRouteImport
      parentRoute: typeof AuthenticatedExpedicaoRoute
    }
    '/_authenticated/expedicao/direcionamento': {
      id: '/_authenticated/expedicao/direcionamento'
      path: '/direcionamento'
      fullPath: '/expedicao/direcionamento'
      preLoaderRoute: typeof AuthenticatedExpedicaoDirecionamentoRouteImport
      parentRoute: typeof AuthenticatedExpedicaoRoute
    }
    '/_authenticated/expedicao/cq': {
      id: '/_authenticated/expedicao/cq'
      path: '/cq'
      fullPath: '/expedicao/cq'
      preLoaderRoute: typeof AuthenticatedExpedicaoCqRouteImport
      parentRoute: typeof AuthenticatedExpedicaoRoute
    }
    '/_authenticated/entrada-saida/os-tecido': {
      id: '/_authenticated/entrada-saida/os-tecido'
      path: '/os-tecido'
      fullPath: '/entrada-saida/os-tecido'
      preLoaderRoute: typeof AuthenticatedEntradaSaidaOsTecidoRouteImport
      parentRoute: typeof AuthenticatedEntradaSaidaRoute
    }
    '/_authenticated/entrada-saida/os-aviamento': {
      id: '/_authenticated/entrada-saida/os-aviamento'
      path: '/os-aviamento'
      fullPath: '/entrada-saida/os-aviamento'
      preLoaderRoute: typeof AuthenticatedEntradaSaidaOsAviamentoRouteImport
      parentRoute: typeof AuthenticatedEntradaSaidaRoute
    }
    '/_authenticated/entrada-saida/oc-tecido': {
      id: '/_authenticated/entrada-saida/oc-tecido'
      path: '/oc-tecido'
      fullPath: '/entrada-saida/oc-tecido'
      preLoaderRoute: typeof AuthenticatedEntradaSaidaOcTecidoRouteImport
      parentRoute: typeof AuthenticatedEntradaSaidaRoute
    }
    '/_authenticated/entrada-saida/oc-p-acabado': {
      id: '/_authenticated/entrada-saida/oc-p-acabado'
      path: '/oc-p-acabado'
      fullPath: '/entrada-saida/oc-p-acabado'
      preLoaderRoute: typeof AuthenticatedEntradaSaidaOcPAcabadoRouteImport
      parentRoute: typeof AuthenticatedEntradaSaidaRoute
    }
    '/_authenticated/entrada-saida/oc-insumo': {
      id: '/_authenticated/entrada-saida/oc-insumo'
      path: '/oc-insumo'
      fullPath: '/entrada-saida/oc-insumo'
      preLoaderRoute: typeof AuthenticatedEntradaSaidaOcInsumoRouteImport
      parentRoute: typeof AuthenticatedEntradaSaidaRoute
    }
    '/_authenticated/entrada-saida/oc-aviamento': {
      id: '/_authenticated/entrada-saida/oc-aviamento'
      path: '/oc-aviamento'
      fullPath: '/entrada-saida/oc-aviamento'
      preLoaderRoute: typeof AuthenticatedEntradaSaidaOcAviamentoRouteImport
      parentRoute: typeof AuthenticatedEntradaSaidaRoute
    }
    '/_authenticated/entrada-saida/explosao': {
      id: '/_authenticated/entrada-saida/explosao'
      path: '/explosao'
      fullPath: '/entrada-saida/explosao'
      preLoaderRoute: typeof AuthenticatedEntradaSaidaExplosaoRouteImport
      parentRoute: typeof AuthenticatedEntradaSaidaRoute
    }
    '/_authenticated/entrada-saida/alertas-tecido': {
      id: '/_authenticated/entrada-saida/alertas-tecido'
      path: '/alertas-tecido'
      fullPath: '/entrada-saida/alertas-tecido'
      preLoaderRoute: typeof AuthenticatedEntradaSaidaAlertasTecidoRouteImport
      parentRoute: typeof AuthenticatedEntradaSaidaRoute
    }
    '/_authenticated/criacao/produto-acabado': {
      id: '/_authenticated/criacao/produto-acabado'
      path: '/produto-acabado'
      fullPath: '/criacao/produto-acabado'
      preLoaderRoute: typeof AuthenticatedCriacaoProdutoAcabadoRouteImport
      parentRoute: typeof AuthenticatedCriacaoRoute
    }
    '/_authenticated/criacao/planejamento': {
      id: '/_authenticated/criacao/planejamento'
      path: '/planejamento'
      fullPath: '/criacao/planejamento'
      preLoaderRoute: typeof AuthenticatedCriacaoPlanejamentoRouteImport
      parentRoute: typeof AuthenticatedCriacaoRoute
    }
    '/_authenticated/criacao/plan-tecido': {
      id: '/_authenticated/criacao/plan-tecido'
      path: '/plan-tecido'
      fullPath: '/criacao/plan-tecido'
      preLoaderRoute: typeof AuthenticatedCriacaoPlanTecidoRouteImport
      parentRoute: typeof AuthenticatedCriacaoRoute
    }
    '/_authenticated/criacao/explosao': {
      id: '/_authenticated/criacao/explosao'
      path: '/explosao'
      fullPath: '/criacao/explosao'
      preLoaderRoute: typeof AuthenticatedCriacaoExplosaoRouteImport
      parentRoute: typeof AuthenticatedCriacaoRoute
    }
    '/_authenticated/criacao/desenvolvimento': {
      id: '/_authenticated/criacao/desenvolvimento'
      path: '/desenvolvimento'
      fullPath: '/criacao/desenvolvimento'
      preLoaderRoute: typeof AuthenticatedCriacaoDesenvolvimentoRouteImport
      parentRoute: typeof AuthenticatedCriacaoRoute
    }
    '/_authenticated/cadastro/tecidos': {
      id: '/_authenticated/cadastro/tecidos'
      path: '/tecidos'
      fullPath: '/cadastro/tecidos'
      preLoaderRoute: typeof AuthenticatedCadastroTecidosRouteImport
      parentRoute: typeof AuthenticatedCadastroRoute
    }
    '/_authenticated/cadastro/servico': {
      id: '/_authenticated/cadastro/servico'
      path: '/servico'
      fullPath: '/cadastro/servico'
      preLoaderRoute: typeof AuthenticatedCadastroServicoRouteImport
      parentRoute: typeof AuthenticatedCadastroRoute
    }
    '/_authenticated/cadastro/lojas': {
      id: '/_authenticated/cadastro/lojas'
      path: '/lojas'
      fullPath: '/cadastro/lojas'
      preLoaderRoute: typeof AuthenticatedCadastroLojasRouteImport
      parentRoute: typeof AuthenticatedCadastroRoute
    }
    '/_authenticated/cadastro/etiquetas': {
      id: '/_authenticated/cadastro/etiquetas'
      path: '/etiquetas'
      fullPath: '/cadastro/etiquetas'
      preLoaderRoute: typeof AuthenticatedCadastroEtiquetasRouteImport
      parentRoute: typeof AuthenticatedCadastroRoute
    }
    '/_authenticated/cadastro/destinos': {
      id: '/_authenticated/cadastro/destinos'
      path: '/destinos'
      fullPath: '/cadastro/destinos'
      preLoaderRoute: typeof AuthenticatedCadastroDestinosRouteImport
      parentRoute: typeof AuthenticatedCadastroRoute
    }
    '/_authenticated/cadastro/colaboradores': {
      id: '/_authenticated/cadastro/colaboradores'
      path: '/colaboradores'
      fullPath: '/cadastro/colaboradores'
      preLoaderRoute: typeof AuthenticatedCadastroColaboradoresRouteImport
      parentRoute: typeof AuthenticatedCadastroRoute
    }
    '/_authenticated/cadastro/aviamentos': {
      id: '/_authenticated/cadastro/aviamentos'
      path: '/aviamentos'
      fullPath: '/cadastro/aviamentos'
      preLoaderRoute: typeof AuthenticatedCadastroAviamentosRouteImport
      parentRoute: typeof AuthenticatedCadastroRoute
    }
    '/_authenticated/cadastro/atributos': {
      id: '/_authenticated/cadastro/atributos'
      path: '/atributos'
      fullPath: '/cadastro/atributos'
      preLoaderRoute: typeof AuthenticatedCadastroAtributosRouteImport
      parentRoute: typeof AuthenticatedCadastroRoute
    }
    '/_authenticated/admin/usuarios-loja': {
      id: '/_authenticated/admin/usuarios-loja'
      path: '/usuarios-loja'
      fullPath: '/admin/usuarios-loja'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosLojaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/lojas': {
      id: '/_authenticated/admin/lojas'
      path: '/lojas'
      fullPath: '/admin/lojas'
      preLoaderRoute: typeof AuthenticatedAdminLojasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/identidade': {
      id: '/_authenticated/admin/identidade'
      path: '/identidade'
      fullPath: '/admin/identidade'
      preLoaderRoute: typeof AuthenticatedAdminIdentidadeRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/configuracoes': {
      id: '/_authenticated/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AuthenticatedAdminConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/pcp/servicos/': {
      id: '/_authenticated/pcp/servicos/'
      path: '/'
      fullPath: '/pcp/servicos/'
      preLoaderRoute: typeof AuthenticatedPcpServicosIndexRouteImport
      parentRoute: typeof AuthenticatedPcpServicosRoute
    }
    '/_authenticated/pcp/oficina/': {
      id: '/_authenticated/pcp/oficina/'
      path: '/'
      fullPath: '/pcp/oficina/'
      preLoaderRoute: typeof AuthenticatedPcpOficinaIndexRouteImport
      parentRoute: typeof AuthenticatedPcpOficinaRoute
    }
    '/_authenticated/pcp/cad/': {
      id: '/_authenticated/pcp/cad/'
      path: '/'
      fullPath: '/pcp/cad/'
      preLoaderRoute: typeof AuthenticatedPcpCadIndexRouteImport
      parentRoute: typeof AuthenticatedPcpCadRoute
    }
    '/_authenticated/expedicao/direcionamento/': {
      id: '/_authenticated/expedicao/direcionamento/'
      path: '/'
      fullPath: '/expedicao/direcionamento/'
      preLoaderRoute: typeof AuthenticatedExpedicaoDirecionamentoIndexRouteImport
      parentRoute: typeof AuthenticatedExpedicaoDirecionamentoRoute
    }
    '/_authenticated/expedicao/cq/': {
      id: '/_authenticated/expedicao/cq/'
      path: '/'
      fullPath: '/expedicao/cq/'
      preLoaderRoute: typeof AuthenticatedExpedicaoCqIndexRouteImport
      parentRoute: typeof AuthenticatedExpedicaoCqRoute
    }
    '/_authenticated/entrada-saida/explosao/': {
      id: '/_authenticated/entrada-saida/explosao/'
      path: '/'
      fullPath: '/entrada-saida/explosao/'
      preLoaderRoute: typeof AuthenticatedEntradaSaidaExplosaoIndexRouteImport
      parentRoute: typeof AuthenticatedEntradaSaidaExplosaoRoute
    }
    '/_authenticated/cadastro/tecidos/': {
      id: '/_authenticated/cadastro/tecidos/'
      path: '/'
      fullPath: '/cadastro/tecidos/'
      preLoaderRoute: typeof AuthenticatedCadastroTecidosIndexRouteImport
      parentRoute: typeof AuthenticatedCadastroTecidosRoute
    }
    '/_authenticated/pcp/servicos/$modeloId': {
      id: '/_authenticated/pcp/servicos/$modeloId'
      path: '/$modeloId'
      fullPath: '/pcp/servicos/$modeloId'
      preLoaderRoute: typeof AuthenticatedPcpServicosModeloIdRouteImport
      parentRoute: typeof AuthenticatedPcpServicosRoute
    }
    '/_authenticated/pcp/oficina/$modeloId': {
      id: '/_authenticated/pcp/oficina/$modeloId'
      path: '/$modeloId'
      fullPath: '/pcp/oficina/$modeloId'
      preLoaderRoute: typeof AuthenticatedPcpOficinaModeloIdRouteImport
      parentRoute: typeof AuthenticatedPcpOficinaRoute
    }
    '/_authenticated/pcp/cad/$modeloId': {
      id: '/_authenticated/pcp/cad/$modeloId'
      path: '/$modeloId'
      fullPath: '/pcp/cad/$modeloId'
      preLoaderRoute: typeof AuthenticatedPcpCadModeloIdRouteImport
      parentRoute: typeof AuthenticatedPcpCadRoute
    }
    '/_authenticated/expedicao/direcionamento/$modeloId': {
      id: '/_authenticated/expedicao/direcionamento/$modeloId'
      path: '/$modeloId'
      fullPath: '/expedicao/direcionamento/$modeloId'
      preLoaderRoute: typeof AuthenticatedExpedicaoDirecionamentoModeloIdRouteImport
      parentRoute: typeof AuthenticatedExpedicaoDirecionamentoRoute
    }
    '/_authenticated/expedicao/cq/$modeloId': {
      id: '/_authenticated/expedicao/cq/$modeloId'
      path: '/$modeloId'
      fullPath: '/expedicao/cq/$modeloId'
      preLoaderRoute: typeof AuthenticatedExpedicaoCqModeloIdRouteImport
      parentRoute: typeof AuthenticatedExpedicaoCqRoute
    }
    '/_authenticated/cadastro/tecidos/$artigoId': {
      id: '/_authenticated/cadastro/tecidos/$artigoId'
      path: '/$artigoId'
      fullPath: '/cadastro/tecidos/$artigoId'
      preLoaderRoute: typeof AuthenticatedCadastroTecidosArtigoIdRouteImport
      parentRoute: typeof AuthenticatedCadastroTecidosRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminConfiguracoesRoute: typeof AuthenticatedAdminConfiguracoesRoute
  AuthenticatedAdminIdentidadeRoute: typeof AuthenticatedAdminIdentidadeRoute
  AuthenticatedAdminLojasRoute: typeof AuthenticatedAdminLojasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminUsuariosLojaRoute: typeof AuthenticatedAdminUsuariosLojaRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
    AuthenticatedAdminConfiguracoesRoute: AuthenticatedAdminConfiguracoesRoute,
    AuthenticatedAdminIdentidadeRoute: AuthenticatedAdminIdentidadeRoute,
    AuthenticatedAdminLojasRoute: AuthenticatedAdminLojasRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminUsuariosLojaRoute: AuthenticatedAdminUsuariosLojaRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedCadastroTecidosRouteChildren {
  AuthenticatedCadastroTecidosArtigoIdRoute: typeof AuthenticatedCadastroTecidosArtigoIdRoute
  AuthenticatedCadastroTecidosIndexRoute: typeof AuthenticatedCadastroTecidosIndexRoute
}

const AuthenticatedCadastroTecidosRouteChildren: AuthenticatedCadastroTecidosRouteChildren =
  {
    AuthenticatedCadastroTecidosArtigoIdRoute:
      AuthenticatedCadastroTecidosArtigoIdRoute,
    AuthenticatedCadastroTecidosIndexRoute:
      AuthenticatedCadastroTecidosIndexRoute,
  }

const AuthenticatedCadastroTecidosRouteWithChildren =
  AuthenticatedCadastroTecidosRoute._addFileChildren(
    AuthenticatedCadastroTecidosRouteChildren,
  )

interface AuthenticatedCadastroRouteChildren {
  AuthenticatedCadastroAtributosRoute: typeof AuthenticatedCadastroAtributosRoute
  AuthenticatedCadastroAviamentosRoute: typeof AuthenticatedCadastroAviamentosRoute
  AuthenticatedCadastroColaboradoresRoute: typeof AuthenticatedCadastroColaboradoresRoute
  AuthenticatedCadastroDestinosRoute: typeof AuthenticatedCadastroDestinosRoute
  AuthenticatedCadastroEtiquetasRoute: typeof AuthenticatedCadastroEtiquetasRoute
  AuthenticatedCadastroLojasRoute: typeof AuthenticatedCadastroLojasRoute
  AuthenticatedCadastroServicoRoute: typeof AuthenticatedCadastroServicoRoute
  AuthenticatedCadastroTecidosRoute: typeof AuthenticatedCadastroTecidosRouteWithChildren
  AuthenticatedCadastroIndexRoute: typeof AuthenticatedCadastroIndexRoute
}

const AuthenticatedCadastroRouteChildren: AuthenticatedCadastroRouteChildren = {
  AuthenticatedCadastroAtributosRoute: AuthenticatedCadastroAtributosRoute,
  AuthenticatedCadastroAviamentosRoute: AuthenticatedCadastroAviamentosRoute,
  AuthenticatedCadastroColaboradoresRoute:
    AuthenticatedCadastroColaboradoresRoute,
  AuthenticatedCadastroDestinosRoute: AuthenticatedCadastroDestinosRoute,
  AuthenticatedCadastroEtiquetasRoute: AuthenticatedCadastroEtiquetasRoute,
  AuthenticatedCadastroLojasRoute: AuthenticatedCadastroLojasRoute,
  AuthenticatedCadastroServicoRoute: AuthenticatedCadastroServicoRoute,
  AuthenticatedCadastroTecidosRoute:
    AuthenticatedCadastroTecidosRouteWithChildren,
  AuthenticatedCadastroIndexRoute: AuthenticatedCadastroIndexRoute,
}

const AuthenticatedCadastroRouteWithChildren =
  AuthenticatedCadastroRoute._addFileChildren(
    AuthenticatedCadastroRouteChildren,
  )

interface AuthenticatedCriacaoRouteChildren {
  AuthenticatedCriacaoDesenvolvimentoRoute: typeof AuthenticatedCriacaoDesenvolvimentoRoute
  AuthenticatedCriacaoExplosaoRoute: typeof AuthenticatedCriacaoExplosaoRoute
  AuthenticatedCriacaoPlanTecidoRoute: typeof AuthenticatedCriacaoPlanTecidoRoute
  AuthenticatedCriacaoPlanejamentoRoute: typeof AuthenticatedCriacaoPlanejamentoRoute
  AuthenticatedCriacaoProdutoAcabadoRoute: typeof AuthenticatedCriacaoProdutoAcabadoRoute
  AuthenticatedCriacaoIndexRoute: typeof AuthenticatedCriacaoIndexRoute
}

const AuthenticatedCriacaoRouteChildren: AuthenticatedCriacaoRouteChildren = {
  AuthenticatedCriacaoDesenvolvimentoRoute:
    AuthenticatedCriacaoDesenvolvimentoRoute,
  AuthenticatedCriacaoExplosaoRoute: AuthenticatedCriacaoExplosaoRoute,
  AuthenticatedCriacaoPlanTecidoRoute: AuthenticatedCriacaoPlanTecidoRoute,
  AuthenticatedCriacaoPlanejamentoRoute: AuthenticatedCriacaoPlanejamentoRoute,
  AuthenticatedCriacaoProdutoAcabadoRoute:
    AuthenticatedCriacaoProdutoAcabadoRoute,
  AuthenticatedCriacaoIndexRoute: AuthenticatedCriacaoIndexRoute,
}

const AuthenticatedCriacaoRouteWithChildren =
  AuthenticatedCriacaoRoute._addFileChildren(AuthenticatedCriacaoRouteChildren)

interface AuthenticatedEntradaSaidaExplosaoRouteChildren {
  AuthenticatedEntradaSaidaExplosaoIndexRoute: typeof AuthenticatedEntradaSaidaExplosaoIndexRoute
}

const AuthenticatedEntradaSaidaExplosaoRouteChildren: AuthenticatedEntradaSaidaExplosaoRouteChildren =
  {
    AuthenticatedEntradaSaidaExplosaoIndexRoute:
      AuthenticatedEntradaSaidaExplosaoIndexRoute,
  }

const AuthenticatedEntradaSaidaExplosaoRouteWithChildren =
  AuthenticatedEntradaSaidaExplosaoRoute._addFileChildren(
    AuthenticatedEntradaSaidaExplosaoRouteChildren,
  )

interface AuthenticatedEntradaSaidaRouteChildren {
  AuthenticatedEntradaSaidaAlertasTecidoRoute: typeof AuthenticatedEntradaSaidaAlertasTecidoRoute
  AuthenticatedEntradaSaidaExplosaoRoute: typeof AuthenticatedEntradaSaidaExplosaoRouteWithChildren
  AuthenticatedEntradaSaidaOcAviamentoRoute: typeof AuthenticatedEntradaSaidaOcAviamentoRoute
  AuthenticatedEntradaSaidaOcInsumoRoute: typeof AuthenticatedEntradaSaidaOcInsumoRoute
  AuthenticatedEntradaSaidaOcPAcabadoRoute: typeof AuthenticatedEntradaSaidaOcPAcabadoRoute
  AuthenticatedEntradaSaidaOcTecidoRoute: typeof AuthenticatedEntradaSaidaOcTecidoRoute
  AuthenticatedEntradaSaidaOsAviamentoRoute: typeof AuthenticatedEntradaSaidaOsAviamentoRoute
  AuthenticatedEntradaSaidaOsTecidoRoute: typeof AuthenticatedEntradaSaidaOsTecidoRoute
  AuthenticatedEntradaSaidaIndexRoute: typeof AuthenticatedEntradaSaidaIndexRoute
}

const AuthenticatedEntradaSaidaRouteChildren: AuthenticatedEntradaSaidaRouteChildren =
  {
    AuthenticatedEntradaSaidaAlertasTecidoRoute:
      AuthenticatedEntradaSaidaAlertasTecidoRoute,
    AuthenticatedEntradaSaidaExplosaoRoute:
      AuthenticatedEntradaSaidaExplosaoRouteWithChildren,
    AuthenticatedEntradaSaidaOcAviamentoRoute:
      AuthenticatedEntradaSaidaOcAviamentoRoute,
    AuthenticatedEntradaSaidaOcInsumoRoute:
      AuthenticatedEntradaSaidaOcInsumoRoute,
    AuthenticatedEntradaSaidaOcPAcabadoRoute:
      AuthenticatedEntradaSaidaOcPAcabadoRoute,
    AuthenticatedEntradaSaidaOcTecidoRoute:
      AuthenticatedEntradaSaidaOcTecidoRoute,
    AuthenticatedEntradaSaidaOsAviamentoRoute:
      AuthenticatedEntradaSaidaOsAviamentoRoute,
    AuthenticatedEntradaSaidaOsTecidoRoute:
      AuthenticatedEntradaSaidaOsTecidoRoute,
    AuthenticatedEntradaSaidaIndexRoute: AuthenticatedEntradaSaidaIndexRoute,
  }

const AuthenticatedEntradaSaidaRouteWithChildren =
  AuthenticatedEntradaSaidaRoute._addFileChildren(
    AuthenticatedEntradaSaidaRouteChildren,
  )

interface AuthenticatedExpedicaoCqRouteChildren {
  AuthenticatedExpedicaoCqModeloIdRoute: typeof AuthenticatedExpedicaoCqModeloIdRoute
  AuthenticatedExpedicaoCqIndexRoute: typeof AuthenticatedExpedicaoCqIndexRoute
}

const AuthenticatedExpedicaoCqRouteChildren: AuthenticatedExpedicaoCqRouteChildren =
  {
    AuthenticatedExpedicaoCqModeloIdRoute:
      AuthenticatedExpedicaoCqModeloIdRoute,
    AuthenticatedExpedicaoCqIndexRoute: AuthenticatedExpedicaoCqIndexRoute,
  }

const AuthenticatedExpedicaoCqRouteWithChildren =
  AuthenticatedExpedicaoCqRoute._addFileChildren(
    AuthenticatedExpedicaoCqRouteChildren,
  )

interface AuthenticatedExpedicaoDirecionamentoRouteChildren {
  AuthenticatedExpedicaoDirecionamentoModeloIdRoute: typeof AuthenticatedExpedicaoDirecionamentoModeloIdRoute
  AuthenticatedExpedicaoDirecionamentoIndexRoute: typeof AuthenticatedExpedicaoDirecionamentoIndexRoute
}

const AuthenticatedExpedicaoDirecionamentoRouteChildren: AuthenticatedExpedicaoDirecionamentoRouteChildren =
  {
    AuthenticatedExpedicaoDirecionamentoModeloIdRoute:
      AuthenticatedExpedicaoDirecionamentoModeloIdRoute,
    AuthenticatedExpedicaoDirecionamentoIndexRoute:
      AuthenticatedExpedicaoDirecionamentoIndexRoute,
  }

const AuthenticatedExpedicaoDirecionamentoRouteWithChildren =
  AuthenticatedExpedicaoDirecionamentoRoute._addFileChildren(
    AuthenticatedExpedicaoDirecionamentoRouteChildren,
  )

interface AuthenticatedExpedicaoRouteChildren {
  AuthenticatedExpedicaoCqRoute: typeof AuthenticatedExpedicaoCqRouteWithChildren
  AuthenticatedExpedicaoDirecionamentoRoute: typeof AuthenticatedExpedicaoDirecionamentoRouteWithChildren
  AuthenticatedExpedicaoLancamentosRoute: typeof AuthenticatedExpedicaoLancamentosRoute
  AuthenticatedExpedicaoIndexRoute: typeof AuthenticatedExpedicaoIndexRoute
}

const AuthenticatedExpedicaoRouteChildren: AuthenticatedExpedicaoRouteChildren =
  {
    AuthenticatedExpedicaoCqRoute: AuthenticatedExpedicaoCqRouteWithChildren,
    AuthenticatedExpedicaoDirecionamentoRoute:
      AuthenticatedExpedicaoDirecionamentoRouteWithChildren,
    AuthenticatedExpedicaoLancamentosRoute:
      AuthenticatedExpedicaoLancamentosRoute,
    AuthenticatedExpedicaoIndexRoute: AuthenticatedExpedicaoIndexRoute,
  }

const AuthenticatedExpedicaoRouteWithChildren =
  AuthenticatedExpedicaoRoute._addFileChildren(
    AuthenticatedExpedicaoRouteChildren,
  )

interface AuthenticatedPcpCadRouteChildren {
  AuthenticatedPcpCadModeloIdRoute: typeof AuthenticatedPcpCadModeloIdRoute
  AuthenticatedPcpCadIndexRoute: typeof AuthenticatedPcpCadIndexRoute
}

const AuthenticatedPcpCadRouteChildren: AuthenticatedPcpCadRouteChildren = {
  AuthenticatedPcpCadModeloIdRoute: AuthenticatedPcpCadModeloIdRoute,
  AuthenticatedPcpCadIndexRoute: AuthenticatedPcpCadIndexRoute,
}

const AuthenticatedPcpCadRouteWithChildren =
  AuthenticatedPcpCadRoute._addFileChildren(AuthenticatedPcpCadRouteChildren)

interface AuthenticatedPcpOficinaRouteChildren {
  AuthenticatedPcpOficinaModeloIdRoute: typeof AuthenticatedPcpOficinaModeloIdRoute
  AuthenticatedPcpOficinaIndexRoute: typeof AuthenticatedPcpOficinaIndexRoute
}

const AuthenticatedPcpOficinaRouteChildren: AuthenticatedPcpOficinaRouteChildren =
  {
    AuthenticatedPcpOficinaModeloIdRoute: AuthenticatedPcpOficinaModeloIdRoute,
    AuthenticatedPcpOficinaIndexRoute: AuthenticatedPcpOficinaIndexRoute,
  }

const AuthenticatedPcpOficinaRouteWithChildren =
  AuthenticatedPcpOficinaRoute._addFileChildren(
    AuthenticatedPcpOficinaRouteChildren,
  )

interface AuthenticatedPcpServicosRouteChildren {
  AuthenticatedPcpServicosModeloIdRoute: typeof AuthenticatedPcpServicosModeloIdRoute
  AuthenticatedPcpServicosIndexRoute: typeof AuthenticatedPcpServicosIndexRoute
}

const AuthenticatedPcpServicosRouteChildren: AuthenticatedPcpServicosRouteChildren =
  {
    AuthenticatedPcpServicosModeloIdRoute:
      AuthenticatedPcpServicosModeloIdRoute,
    AuthenticatedPcpServicosIndexRoute: AuthenticatedPcpServicosIndexRoute,
  }

const AuthenticatedPcpServicosRouteWithChildren =
  AuthenticatedPcpServicosRoute._addFileChildren(
    AuthenticatedPcpServicosRouteChildren,
  )

interface AuthenticatedPcpRouteChildren {
  AuthenticatedPcpCadRoute: typeof AuthenticatedPcpCadRouteWithChildren
  AuthenticatedPcpOficinaRoute: typeof AuthenticatedPcpOficinaRouteWithChildren
  AuthenticatedPcpServicosRoute: typeof AuthenticatedPcpServicosRouteWithChildren
  AuthenticatedPcpIndexRoute: typeof AuthenticatedPcpIndexRoute
}

const AuthenticatedPcpRouteChildren: AuthenticatedPcpRouteChildren = {
  AuthenticatedPcpCadRoute: AuthenticatedPcpCadRouteWithChildren,
  AuthenticatedPcpOficinaRoute: AuthenticatedPcpOficinaRouteWithChildren,
  AuthenticatedPcpServicosRoute: AuthenticatedPcpServicosRouteWithChildren,
  AuthenticatedPcpIndexRoute: AuthenticatedPcpIndexRoute,
}

const AuthenticatedPcpRouteWithChildren =
  AuthenticatedPcpRoute._addFileChildren(AuthenticatedPcpRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCadastroRoute: typeof AuthenticatedCadastroRouteWithChildren
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCriacaoRoute: typeof AuthenticatedCriacaoRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEntradaSaidaRoute: typeof AuthenticatedEntradaSaidaRouteWithChildren
  AuthenticatedExpedicaoRoute: typeof AuthenticatedExpedicaoRouteWithChildren
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedPcpRoute: typeof AuthenticatedPcpRouteWithChildren
  AuthenticatedOtbIndexRoute: typeof AuthenticatedOtbIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCadastroRoute: AuthenticatedCadastroRouteWithChildren,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCriacaoRoute: AuthenticatedCriacaoRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEntradaSaidaRoute: AuthenticatedEntradaSaidaRouteWithChildren,
  AuthenticatedExpedicaoRoute: AuthenticatedExpedicaoRouteWithChildren,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedPcpRoute: AuthenticatedPcpRouteWithChildren,
  AuthenticatedOtbIndexRoute: AuthenticatedOtbIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
