/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProducaoRouteImport } from './routes/_authenticated/producao'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEntradaSaidaRouteImport } from './routes/_authenticated/entrada-saida'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCriacaoRouteImport } from './routes/_authenticated/criacao'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCadastroRouteImport } from './routes/_authenticated/cadastro'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminUsuariosLojaRouteImport } from './routes/_authenticated/admin/usuarios-loja'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminLojasRouteImport } from './routes/_authenticated/admin/lojas'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProducaoRoute = AuthenticatedProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEntradaSaidaRoute =
  AuthenticatedEntradaSaidaRouteImport.update({
    id: '/entrada-saida',
    path: '/entrada-saida',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCriacaoRoute = AuthenticatedCriacaoRouteImport.update({
  id: '/criacao',
  path: '/criacao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCadastroRoute = AuthenticatedCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsuariosLojaRoute =
  AuthenticatedAdminUsuariosLojaRouteImport.update({
    id: '/usuarios-loja',
    path: '/usuarios-loja',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLojasRoute = AuthenticatedAdminLojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/cadastro': typeof AuthenticatedCadastroRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/criacao': typeof AuthenticatedCriacaoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entrada-saida': typeof AuthenticatedEntradaSaidaRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/admin/lojas': typeof AuthenticatedAdminLojasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/usuarios-loja': typeof AuthenticatedAdminUsuariosLojaRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro': typeof AuthenticatedCadastroRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/criacao': typeof AuthenticatedCriacaoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/entrada-saida': typeof AuthenticatedEntradaSaidaRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/admin/lojas': typeof AuthenticatedAdminLojasRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/admin/usuarios-loja': typeof AuthenticatedAdminUsuariosLojaRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/cadastro': typeof AuthenticatedCadastroRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/criacao': typeof AuthenticatedCriacaoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/entrada-saida': typeof AuthenticatedEntradaSaidaRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/producao': typeof AuthenticatedProducaoRoute
  '/_authenticated/admin/lojas': typeof AuthenticatedAdminLojasRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/admin/usuarios-loja': typeof AuthenticatedAdminUsuariosLojaRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/cadastro'
    | '/configuracoes'
    | '/criacao'
    | '/dashboard'
    | '/entrada-saida'
    | '/financeiro'
    | '/producao'
    | '/admin/lojas'
    | '/admin/usuarios'
    | '/admin/usuarios-loja'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cadastro'
    | '/configuracoes'
    | '/criacao'
    | '/dashboard'
    | '/entrada-saida'
    | '/financeiro'
    | '/producao'
    | '/admin/lojas'
    | '/admin/usuarios'
    | '/admin/usuarios-loja'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/cadastro'
    | '/_authenticated/configuracoes'
    | '/_authenticated/criacao'
    | '/_authenticated/dashboard'
    | '/_authenticated/entrada-saida'
    | '/_authenticated/financeiro'
    | '/_authenticated/producao'
    | '/_authenticated/admin/lojas'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/admin/usuarios-loja'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/producao': {
      id: '/_authenticated/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AuthenticatedProducaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/entrada-saida': {
      id: '/_authenticated/entrada-saida'
      path: '/entrada-saida'
      fullPath: '/entrada-saida'
      preLoaderRoute: typeof AuthenticatedEntradaSaidaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/criacao': {
      id: '/_authenticated/criacao'
      path: '/criacao'
      fullPath: '/criacao'
      preLoaderRoute: typeof AuthenticatedCriacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cadastro': {
      id: '/_authenticated/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof AuthenticatedCadastroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios-loja': {
      id: '/_authenticated/admin/usuarios-loja'
      path: '/usuarios-loja'
      fullPath: '/admin/usuarios-loja'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosLojaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/lojas': {
      id: '/_authenticated/admin/lojas'
      path: '/lojas'
      fullPath: '/admin/lojas'
      preLoaderRoute: typeof AuthenticatedAdminLojasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminLojasRoute: typeof AuthenticatedAdminLojasRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminUsuariosLojaRoute: typeof AuthenticatedAdminUsuariosLojaRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminLojasRoute: AuthenticatedAdminLojasRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
  AuthenticatedAdminUsuariosLojaRoute: AuthenticatedAdminUsuariosLojaRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCadastroRoute: typeof AuthenticatedCadastroRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCriacaoRoute: typeof AuthenticatedCriacaoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEntradaSaidaRoute: typeof AuthenticatedEntradaSaidaRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedProducaoRoute: typeof AuthenticatedProducaoRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCadastroRoute: AuthenticatedCadastroRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCriacaoRoute: AuthenticatedCriacaoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEntradaSaidaRoute: AuthenticatedEntradaSaidaRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedProducaoRoute: AuthenticatedProducaoRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
